### ISSUE TITLE
Incorrect package warning on create release page for Git projects that deploy child releases

### ISSUE THREAD

**Issue by dylanlerch** [OctopusDeploy/Issues#7687] opened 2022-07-25 22:50 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Showing incorrect warnings, mostly visual but requires 

### Version

Discovered in 2022.2.7388

### What happened?

In a Git project, when creating a release for a project that deploys child releases, a `<Package Name> could not be found in Octopus Server Releases (built-in)` warning is shown next to all the release versions.

![image](https://user-images.githubusercontent.com/83607909/180896557-49d6982e-2c6d-457b-bfb5-5be268272064.png)

### Reproduction

- Create a project that deploys a release on another project
- Convert the project to Git 
- Observe warning icon next to the package names for the child releases

### More Information

Original report [internal] - https://octopus.zendesk.com/agent/tickets/93445

### Workaround

Release creation is not blocked. The misleading warnings can be ignored.

**Comment by YuKitsune** [comment] 2022-08-05 05:29
Seems to be related to OctopusDeploy/Issues#7704
I'm unable to reproduce this since the fix for that issue was merged.

**Closed by YuKitsune** 2022-08-05 05:29 UTC
Labels: kind/bug, priority/low, state/triage, team/config-as-code
