### ISSUE TITLE
Message Bus error post upgrade

### ISSUE THREAD

**Issue by michaelongso** [OctopusDeploy/Issues#7993] opened 2023-01-16 00:57 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Can prevent important activities such as running tasks.

### Version

Version before 2022.4.4002

### Latest Version

Can be reproduced on the latest version.

### What happened?

Issue post upgrade from version pre-2022.4.4002 to version after (IE: 2022.4.8319) with message,

```
Failed to pump events in the message bus"...
Error resolving type specified in JSON 'Octopus.Core.Model.ServerTasks.ServerTaskCancelledEvent, Octopus.Core' 
```

This issue occurs when attempting to perform an upgrade while another instance of Octopus Server is still running. The data contract has changed between the two versions, which means the "old" version will be writing events to the database that the "new" version cannot read. Please make sure to follow the [upgrade instructions](https://octopus.com/docs/administration/upgrading/guide/upgrading-minor-and-patch-releases#standard-upgrade-process) carefully.

### Reproduction

1. Run two instances of Octopus Server against the same database at a pre-2022.4.4002 version
2. Shut down one of instances and upgrade it to 2022.4.8319, leaving the other instance running
3. Once the upgrade completes, start the upgraded instance again
4. Observe the above errors appearing in the logs

### Error and Stacktrace

```shell
Failed to pump events in the message bus", attempt 101. Trying again after 00:00:17.9007323... 
Nevermore.ReaderException: Error reading row 33, column 4. Error resolving type specified in JSON 'Octopus.Core.Model.ServerTasks.ServerTaskCancelledEvent, Octopus.Core'. Path 'Payload.$type', line 1, position 123
```

### More Information

- This was raised on a HA setup running 4 nodes.
- The entries for the MessageBusEvent table post-upgrade indicate that the upgrade script did not run successfully on **some row**. (Skipped? Need more data points for investigation)
  - It appears that the upgrade did run successfully, but another Octopus Server instance was running which continued to generate data in the old format

For **Customer** facing this issue please raise a support ticket. It will allow for additional investigation data.

### Workaround

Run SQL script to align MessageBusEvent table
_(Please note that it may take time to "align" once the SQL script has run. During this time, you may see timeouts in your Octopus Server logs)_
```
BEGIN TRANSACTION
UPDATE MessageBusEvent
SET [PayloadType] = 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskCancelledEvent, Octopus.Core',
    [JSON] = JSON_MODIFY(JSON, '$.Payload."$type"', 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskCancelledEvent, Octopus.Core')

WHERE JSON_VALUE(JSON, '$.Payload."$type"') = 'Octopus.Core.Model.ServerTasks.ServerTaskCancelledEvent, Octopus.Core'

UPDATE MessageBusEvent
SET [PayloadType] = 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskQueuedEvent, Octopus.Core',
    [JSON] = JSON_MODIFY(JSON, '$.Payload."$type"', 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskQueuedEvent, Octopus.Core')

WHERE JSON_VALUE(JSON, '$.Payload."$type"') = 'Octopus.Core.Model.ServerTasks.ServerTaskQueuedEvent, Octopus.Core'

UPDATE MessageBusEvent
SET [PayloadType] = 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskSucceededEvent, Octopus.Core',
    [JSON] = JSON_MODIFY(JSON, '$.Payload."$type"', 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskSucceededEvent, Octopus.Core')

WHERE JSON_VALUE(JSON, '$.Payload."$type"') = 'Octopus.Core.Model.ServerTasks.ServerTaskSucceededEvent, Octopus.Core'

UPDATE MessageBusEvent
SET [PayloadType] = 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskFailedEvent, Octopus.Core',
    [JSON] = JSON_MODIFY(JSON, '$.Payload."$type"', 'Octopus.Core.Features.ServerTasks.MessageContracts.ServerTaskFailedEvent, Octopus.Core')

WHERE JSON_VALUE(JSON, '$.Payload."$type"') = 'Octopus.Core.Model.ServerTasks.ServerTaskFailedEvent, Octopus.Core'
COMMIT
```

**Comment by embusalacchi** [comment] 2023-01-17 19:08
FYI: I am experiencing this error on a non-HA deployment.

**Comment by embusalacchi** [comment] 2023-01-18 02:44
Actually, the error seems to be slightly different:

`
2023-01-18 02:40:38.5668   3656    195 ERROR  "Failed to pump events in the message bus", attempt 28. Trying again after 00:00:24.1708730...
Nevermore.ReaderException: Error reading row 1, column 4. Error resolving type specified in JSON 'Octopus.Core.Model.ServerTasks.ServerTaskQueuedEvent, Octopus.Core'. Path 'Payload.$type', line 1, position 119..
Compiled reader expression:
 
(DbDataReader reader, DocumentReaderContext context) =>
{
    Type deserializeAsType = Octopus.Core.Infrastructure.MessageBus.MessageBusEvent
    context.Column = 0
    String temp0 = IIF(reader.IsDBNull(0), null, reader.GetString(0))
    context.Column = 1
    Int64 temp1 = reader.GetInt64(1)
    context.Column = 2
    String temp2 = IIF(reader.IsDBNull(2), null, reader.GetString(2))
    context.Column = 3
    DateTimeOffset temp3 = IIF(reader.IsDBNull(3), default(DateTimeOffset), Convert(reader.GetValue(3), DateTimeOffset))
    context.Column = 4
    MessageBusEvent deserializedFromJson = context.DeserializeText(reader, 4, deserializeAsType)
    MessageBusEvent result = deserializedFromJson
    if (result != null)
    {
        result.Id = temp0
        result.SequenceNumber = temp1
        result.PayloadType = temp2
        result.Created = temp3
    }
 
    result
}
 
---> Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'Octopus.Core.Model.ServerTasks.ServerTaskQueuedEvent, Octopus.Core'. Path 'Payload.$type', line 1, position 119.
---> Newtonsoft.Json.JsonSerializationException: Could not find type 'Octopus.Core.Model.ServerTasks.ServerTaskQueuedEvent' in assembly 'Octopus.Core, Version=2022.4.8332.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Nevermore.Advanced.Serialization.NewtonsoftDocumentSerializer.DeserializeSmallText(String text, Type type)
   at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderContext.DeserializeText[TDocument](DbDataReader reader, Int32 index, Type concreteType)
   at lambda_method2828(Closure , DbDataReader , DocumentReaderContext )
   at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.<>c__DisplayClass4_1`1.<CreateReader>b__1(DbDataReader dbDataReader)
   --- End of inner exception stack trace ---
   at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.<>c__DisplayClass4_1`1.<CreateReader>b__1(DbDataReader dbDataReader)
   at Nevermore.Advanced.ReadTransaction.ProcessReaderAsync[TRecord](DbDataReader reader, PreparedCommand command, CancellationToken cancellationToken)+MoveNext()
   at Nevermore.Advanced.ReadTransaction.ProcessReaderAsync[TRecord](DbDataReader reader, PreparedCommand command, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Nevermore.Advanced.ReadTransaction.<>c__DisplayClass101_0`1.<<StreamAsync>g__Execute|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nevermore.Advanced.ReadTransaction.<>c__DisplayClass101_0`1.<<StreamAsync>g__Execute|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nevermore.Advanced.ReadTransaction.<>c__DisplayClass101_0`1.<<StreamAsync>g__Execute|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nevermore.Advanced.ReadTransaction.<>c__DisplayClass101_0`1.<<StreamAsync>g__Execute|0>d.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Nevermore.Advanced.ThreadSafeAsyncEnumerable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Nevermore.Advanced.ThreadSafeAsyncEnumerable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Nevermore.Advanced.ThreadSafeAsyncEnumerable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at Octopus.Core.Infrastructure.MessageBus.Transports.SqlServer.SqlMessageBusTransport.GetNextEventAfter(Int64 cursorSequenceNumber, IRawReadQueryExecutor tx, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/MessageBus/Transports/SqlServer/SqlMessageBusTransport.cs:line 235
   at Octopus.Core.Infrastructure.MessageBus.Transports.SqlServer.SqlMessageBusTransport.DispatchPendingEventsFor(String consumerGroupId, StartingPoint startingPoint, Func`3 dispatchAction, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/MessageBus/Transports/SqlServer/SqlMessageBusTransport.cs:line 153
   at Octopus.Core.Infrastructure.MessageBus.Transports.SqlServer.SqlMessageBusTransport.DispatchPendingEventsFor(String consumerGroupId, StartingPoint startingPoint, Func`3 dispatchAction, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/MessageBus/Transports/SqlServer/SqlMessageBusTransport.cs:line 166
   at Octopus.Core.Infrastructure.MessageBus.Transports.SqlServer.SqlTransportCrossClusterDecorator.DispatchPendingEventsFor(String consumerGroupId, StartingPoint startingPoint, Func`3 dispatchAction, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/MessageBus/Transports/SqlServer/SqlTransportCrossClusterDecorator.cs:line 59
   at Octopus.Core.Infrastructure.MessageBus.MessagePump.<PumpMessages>b__12_0(CancellationToken ct) in ./source/Octopus.Core/Infrastructure/MessageBus/MessagePump.cs:line 98
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
`

**Comment by michaelongso** [comment] 2023-01-18 06:09
Hi @embusalacchi, there seems to be more than one event type that didn't upgrade properly. There's an updated script on the support ticket, please let us know if that doesn't solve the issue. Thanks.

**Comment by millerjn21** [comment] 2023-01-18 15:08
Internal Ticket referenced above by michael: https://octopus.zendesk.com/agent/tickets/105475

**Comment by embusalacchi** [comment] 2023-01-18 15:39
> Internal Ticket referenced above by michael: https://octopus.zendesk.com/agent/tickets/105475

Yes, the most recent SQL Statement from Support fixed the issue.

**Comment by adam-mccoy** [comment] 2023-01-24 06:01
There is not a bug here in the typical sense, but it is a bit too easy to wind up in a situation like this. We'll investigate options that will help customers avoid inadvertently encountering this. One option might be to detect older versions of Octopus Server running against the database and block the upgrade process.

**Closed by adam-mccoy** 2023-01-24 06:01 UTC
Labels: kind/bug, state/triage, team/core-platform

**Comment by KennethBates** [comment] 2023-02-03 01:05
Another instance of this issue, however this time with the UserLoginSucceededEvent not being upgraded in the MessageBusEvent table.
Source: https://octopus.zendesk.com/agent/tickets/106359 (private)

The solution in this case, where there were 2 nodes, both upgraded, was the following.

1. Put Octopus in maintenance mode
2. Stop all nodes connected to the database instance listed under Configuration > Nodes
3. Take a backup of the database before running the below script
4. Lastly, run the below SQL upgrade script.
 
```
BEGIN TRANSACTION
UPDATE MessageBusEvent
SET [PayloadType] = 'Octopus.Core.Features.Users.MessageContracts.UserLoginSucceededEvent, Octopus.Core',
    [JSON] = JSON_MODIFY(JSON, '$.Payload."$type"', 'Octopus.Core.Features.Users.MessageContracts.UserLoginSucceededEvent, Octopus.Core')

WHERE JSON_VALUE(JSON, '$.Payload."$type"') = 'Octopus.Core.Features.Users.UserLoginSucceededEvent, Octopus.Core'

COMMIT
```

**Comment by Octobob** [comment] 2023-02-12 02:21
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8433 |
| 2023.1 | _tbc_ |

**Comment by Octobob** [comment] 2023-02-13 00:28
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8433 |
| 2023.1 | 2023.1.8978 |

**Comment by adam-mccoy** [comment] 2023-02-13 03:55
Release Note: Fix message bus error when encountering old message format

**Comment by Octobob** [comment] 2023-02-17 06:47
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.4 | 2022.4.8433 |
| 2023.1 | 2023.1.8978 |
| 2023.2+ | _all releases_ |
