### ISSUE TITLE
Package acquisition doesn't account for machine roles in scoping variables

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#6149] opened 2020-02-05 00:09 UTC
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you have a scenario where groups of machines need to use different package feeds, one way to accomplish this is to assign the machines a Role that identifies the feed. E.g some machines might have role `PackageServer1` and others might have `PackageServer2`. Variables for the FeedId can then be scoped to the Role and on conventional steps the correct value is resolved.

However, during package acquisition the process isn't applying the machine's roles correctly and the wrong variable can be resolved.

## What I expected to happen

Package acquisition should observe the same rules as the standard steps. Or we should have a better way of model this, an `Edge` server is one idea we've floated around this in the past.

## Links

https://secure.helpscout.net/conversation/1074146786/56777?folderId=909887

**Comment by droyad** [comment] 2020-02-05 00:22
Duplicate of #2920

**Closed by droyad** 2020-02-05 00:22 UTC
Labels: kind/bug
