### ISSUE TITLE
Invalid resource ids are accepted in variable scope

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#4127] opened 2018-01-02 02:58 UTC
You can specify `Text1-Text2` as Environment Id in a variable scope and as long as your user is not restricted to a specific list of environments. Document Ids seem to follow one of two patterns in Octopus:

- ResourceName_Number, eg. `Environments-1`
- ResournceName-DocumentName, e.g `Feeds-feed-name`

**Possible solution**

Make `DocumentIdParser` smarter so it uses a specific list of prefixes instead of a generic regex.  

Source: https://help.octopusdeploy.com/discussions/problems/66410

**Comment by NickJosevski** [comment] 2018-01-02 04:39
There's a 3rd type for tags in tag sets `TagSet-20\Tags-1` 

Are there any legacy/old/other ids in customer data or other parts of the app that may be impacted by a change where it's got stricter enforcement? Might need to check with Henrik, Mark S, or Mike R.

**Comment by NickJosevski** [comment] 2019-03-21 04:28
Duplicate of: https://github.com/OctopusDeploy/Issues/issues/3538

**Closed by NickJosevski** 2019-03-21 04:28 UTC
Labels: area/modelling, kind/bug
