### ISSUE TITLE
Failed health check icons are incorrect

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#2018] opened 2015-09-22 03:12 UTC
If a health check fails, the icon displayed is a green tick instead of a red cross.  Also heard of this issue happening with Tentacle update.

**Comment by tothegills** [comment] 2015-09-22 03:13
![image](https://cloud.githubusercontent.com/assets/171197/10010247/ad771a2a-612b-11e5-823b-0aff34cb4d92.png)

**Comment by zentron** [comment] 2015-11-06 07:17
Fixed By: https://github.com/OctopusDeploy/OctopusDeploy/commit/571051d8eb32f9c9db72dab29abd47e8e638c7f4

**Comment by zentron** [comment] 2015-11-06 07:18
Release Note: Tasks with error messages cause parent tasks/nodes to also be in a error state.

**Comment by zentron** [comment] 2015-11-08 23:04
Fixed By: https://github.com/OctopusDeploy/OctopusDeploy/commit/571051d8eb32f9c9db72dab29abd47e8e638c7f4

**Comment by zentron** [comment] 2015-11-10 01:38
This appears to be by design as evident by unit test `ActivityLogTreeNodeFixture.ShouldBuildTree` although seems a little odd.
As a result this change is being temporarily reverted

**Comment by PaulStovell** [comment] 2015-11-11 01:46
Looks like a bug (I'm pretty sure it worked before). The machines that fail should be red. The overall task will still be green since the health check "passed" (some machines were just unavailable as is sometimes expected).

**Comment by zentron** [comment] 2015-11-12 02:46
Just a note that `3.0.24` had related bug
![image](https://cloud.githubusercontent.com/assets/1830666/11109342/3575cac0-893b-11e5-883b-74359b0d93d2.png)

**Closed** 2015-11-16 01:23 UTC
Labels: bug, forreview
