### ISSUE TITLE
Release versioning not possible from the included package of a Run Script step if that step is defined to run the script from a different package

### ISSUE THREAD

**Issue by dbsanfte** [OctopusDeploy/Issues#7336] opened 2022-01-26 13:20 UTC
### Team

- [ ] I've assigned a team label to this issue

### Version

2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

The UI will not allow you to set the Project versioning scheme to take the version from the included package on a Run Script step if that step is also set to run the script from a different package.

### Reproduction

Steps to reproduce:

1) Define a project with a Process with a single step: Run Script, that runs a script from say a Github feed package
2) Define an included package on the above step, separate to the package the script is run from
3) Attempt to alter the versioning scheme on the Project to use the "included package" on the above step
4) You should see two packages in the dropdown, but only the first (the package the script is run from) is selectable

Result:

The included package appears in the UI dropdown when choosing the project versioning, but when you select it it does not appear in the selection box. It chooses the script's source package instead. It seems to be impossible to select the included package on the step to be the versioning of the project.

### Workaround
Define a "run script" step that runs an inline script and includes the package you want to version from. You will be able to select this package as a versioning source.

**Comment by dbsanfte** [comment] 2022-01-26 13:30
Tried to add a team label to this issue but no joy.

**Comment by droyad** [comment] 2022-01-26 23:08
I can [reproduce this](https://main.testoctopus.app/app#/Spaces-203/projects/azure-script/deployments/settings) on 2021.3 but not [on 2021.2](https://2021-2.testoctopus.app/app#/Spaces-1/projects/test/deployments/settings)

**Comment by droyad** [comment] 2022-01-26 23:09
@dbsanfte Please contact our [support team](https://octopus.com/support) so your issue can get prioritised and dispatched to the right team.

**Comment by droyad** [comment] 2022-01-26 23:10
Looks like the `/` is ignored for typeahead as both entries here are highlighted
![image](https://user-images.githubusercontent.com/1687639/151262533-a0895372-88b1-4d0b-86ba-82634b01bc8a.png)

**Comment by TomPeters** [comment] 2022-01-26 23:24
At a glance this looks like a modelling issue, where we try to find the matching deployment action by id only and ignore the package, effectively assuming that each action only contains one package: https://github.com/OctopusDeploy/OctopusDeploy/blob/master/newportal/app/areas/projects/components/DeploymentProcessSettings/ReleaseVersionFromPackageSelector.tsx#L25-L36

This doesn't look like an issue with a primitive UI component (even though there's a separate piece of work we could do to ensure the select component fails hard instead of showing two items as being simultaneously selected), so I'm reassigning to #team-fire-and-motion

**Comment by KennethBates** [comment] 2022-01-27 00:58
Possible duplicate of https://github.com/OctopusDeploy/Issues/issues/7283

**Comment by droyad** [comment] 2022-01-27 01:31
Closed as duplicate

**Closed by droyad** 2022-01-27 01:31 UTC
Labels: kind/bug, state/triage, team/fire-and-motion
