### ISSUE TITLE
$OctopusParameters['Octopus.Action.Package.NugetPackageVersion'] is empty

### ISSUE THREAD

**Issue by rikbosch** [OctopusDeploy/Issues#2683] opened 2016-08-30 06:13 UTC
Hi,

After our server upgrade to 3.4.2. The parameter OctopusParameters['Octopus.Action.Package.NugetPackageVersion']  is empty in the deployment step of a package.

Please find the logs below.

`08:03:27   Verbose  |       [Octopus.Action.Number] = '5.1'
08:03:27   Verbose  |       [Octopus.Action.StepName] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Step.Number] = '5'
08:03:27   Verbose  |       [Octopus.Action.Package.PackageVersion] = '2.16.11.14590-beta'
08:03:27   Verbose  |       [Octopus.Step.Id] = '74cfdefa-093d-43db-bd74-7c69a3c8a200'
08:03:27   Verbose  |       [Octopus.Step.Name] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Action.TargetRoles] = 'AppServer'
08:03:27   Verbose  |       [Octopus.Action.Id] = 'f4cb1725-3cc6-42db-89d7-9cb00e5b90d1'
08:03:27   Verbose  |       [Octopus.Action.Name] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Action.Package.FeedId] = 'feeds-rgb-nuget'
08:03:27   Verbose  |       [Octopus.Action.EnabledFeatures] = 'Octopus.Features.CustomScripts,Octopus.Features.ConfigurationVariables'
08:03:27   Verbose  |       [Octopus.Action.Package.AutomaticallyRunConfigurationTransformationFiles] = 'False'
08:03:27   Verbose  |       [Octopus.Action.Package.AutomaticallyUpdateAppSettingsAndConnectionStrings] = 'True'
08:03:27   Verbose  |       [Octopus.Action.Package.DownloadOnTentacle] = 'False'
08:03:27   Verbose  |       [Octopus.Action.Package.PackageId] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Number] = '5.1'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].StepName] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.PackageVersion] = '2.16.11.14590-beta'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.NuGetPackageVersion] = '2.16.11.14590-beta'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].TargetRoles] = 'AppServer'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Id] = 'f4cb1725-3cc6-42db-89d7-9cb00e5b90d1'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Name] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.FeedId] = 'feeds-rgb-nuget'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.NuGetFeedId] = 'feeds-rgb-nuget'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].EnabledFeatures] = 'Octopus.Features.CustomScripts,Octopus.Features.ConfigurationVariables'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.AutomaticallyRunConfigurationTransformationFiles] = 'False'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.AutomaticallyUpdateAppSettingsAndConnectionStrings] = 'True'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.DownloadOnTentacle] = 'False'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.PackageId] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Action[Transplan.Shell.App].Package.NuGetPackageId] = 'Transplan.Shell.App'
08:03:27   Verbose  |       [Octopus.Step[Transplan.Shell.App].Number] = '5'
08:03:27   Verbose  |       [Octopus.Step[Transplan.Shell.App].Id] = '74cfdefa-093d-43db-bd74-7c69a3c8a200'
08:03:27   Verbose  |       [Octopus.Step[Transplan.Shell.App].Name] = 'Transplan.Shell.App'
`

**Comment by michaelnoonan** [comment] 2016-08-31 03:44
Hi, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues as per our [contributing guide](https://github.com/OctopusDeploy/Issues/blob/master/CONTRIBUTING.md).
Looking forward to helping you sort out what's going wrong.
[Why was this closed?](https://octopus.com/company/roadmap/why-was-this-closed)

This looks like a duplicate of https://github.com/OctopusDeploy/Issues/issues/2679 :)

**Closed** 2016-08-31 03:47 UTC
Labels: duplicate
