### ISSUE TITLE
Deploy a Release steps cleared in channel version rules dropdown

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#5867] opened 2019-09-23 02:55 UTC
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If you have version rules configured for `Deploy a Release` steps, the dropdown on the version rule clears all of the selected steps. Whereas any package steps in the version rule remain.

## Steps to reproduce

1. Configure a `Deploy a Release` step
2. Create a channel version rule, specifying this step
3. Save
4. Click the version rule dropdown

### Screen capture

![deploy_a_release_version_rule](https://user-images.githubusercontent.com/20388190/65399495-49246900-de00-11e9-92db-d5cabc525d67.gif)

## Affected versions

Reported in 2019.2.4 and reproduced in 2019.8.4

**Octopus Server:** 

## Links

Source: https://help.octopus.com/t/channel-version-rule-with-multiple-steps/23896

**Comment by droyad** [comment] 2019-09-23 03:13
Duplicate of #5866

**Closed by droyad** 2019-09-23 03:13 UTC
Labels: kind/bug
