### ISSUE TITLE
Unable to load project after renaming runbook step if the step uses the same package as the step used for versioning strategy

### ISSUE THREAD

**Issue by N-lson** [OctopusDeploy/Issues#7230] opened 2021-12-02 05:13 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Can block an entire project

### Version

2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If the project versioning strategy is set to a package step in the deployment process and there is a runbook which also uses that package in a step, if you rename the runbook step the versioning strategy will repoint to the new name of the runbook step. This causes the project to fail to load as the deployment settings are loaded when retrieving project details, and the versioning strategy fails to load as it expects a step with the same name in the deployment process.

### Reproduction

1. Have a deployment process with a package step
2. Set the project versioning strategy to that step
3. Create a runbook with a package step using the same package
4. Update the name of the runbook step
5. 💥 

### Error and Stacktrace

```shell
The resource '<New Step Name>' was not found.
```

### More Information

Internal ticket: https://octopus.zendesk.com/agent/tickets/80171
Internal slack thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1638414770015700

### Workaround

Use the following script: https://github.com/OctopusDeploy/SupportTools/blob/master/OctopusApi/ResetBrokenDeploymentSettings.ps1

Otherwise the deployment settings of the project must be directly altered via SQL to repoint the versioning strategy to an existing step name.

**Comment by henderjm** [comment] 2021-12-05 13:10
I think we have encountered this problem on octopus cloud. Is there a workaround for a cloud instance?

**Comment by N-lson** [comment] 2021-12-06 00:08
Hi @henderjm thanks for the question! Unfortunately there isn't a workaround for cloud instances at the moment. Could you please send an email to support@octopus.com and we'll be happy to help you further with this issue.

**Comment by patrick-smergut-octopus** [comment] 2022-01-26 23:00
Another report of this here: https://help.octopus.com/t/bug-report-release-versioning-based-on-package-breaks-when-updating-a-runbook-step-using-the-same-package/27597/3

**Comment by YuKitsune** [comment] 2022-04-10 22:43
Looks like this is a duplicate of https://github.com/OctopusDeploy/Issues/issues/7242
Closing.

**Closed by YuKitsune** 2022-04-10 22:43 UTC
Labels: kind/bug, state/triage, team/config-as-code
