### ISSUE TITLE
Include Usage accounts in UI

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3989] opened 2017-11-28 04:51 UTC
We have an API that can provide information about where an Azure account is being used. This is the same information we use to know whether we should allow deletion.

It would be helpful to the customers in some scenarios if they could see this information.

Source https://help.octopusdeploy.com/discussions/questions/15330

**Comment by Dalmirog** [comment] 2017-12-04 13:25
![](https://github.trello.services/images/mini-trello-icon.png) [Show account usage in UI](https://trello.com/c/xuh8PH0I/477-show-account-usage-in-ui)

**Comment by Dalmirog** [comment] 2018-02-06 23:45
duplicate of #3980

**Closed by Dalmirog** 2018-02-06 23:45 UTC
Labels: area/Integration, enhancement
