### ISSUE TITLE
User Invites menu item shows up temporarily and then disappears

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7476] opened 2022-04-12 00:28 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Low impact

### Version

Current

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When clicking around items in the Configuration section, the User Invites menu items flickers.

![menu-item-appears](https://user-images.githubusercontent.com/171197/162854414-5dd7d2b5-8f69-4dbc-a920-48af9ad6cd44.gif)

If you are quick:
![image](https://user-images.githubusercontent.com/171197/162854528-94846ee1-bbce-4f13-9535-0196a68cf30c.png)

### Reproduction

Have whatever condition is required to hide the User Invites menu item and click around the other menu items.

### More Information

[Request](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1649654790883659)

**Comment by octokhor** [comment] 2022-08-24 05:33
Will be closing this - very low priority. Still functions as intended, despite the flickering. Closing this unless it becomes a bigger annoyance in the future.

**Closed by octokhor** 2022-08-24 05:33 UTC
Labels: kind/bug, priority/low, state/backlog, team/fire-and-motion, backloggrooming/discussed
