### ISSUE TITLE
Permissions incorrect when Admin user exists in lower-permission Team

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3250] opened 2017-03-03 07:22 UTC
Permissions are incorrect in the case where a User (Admin) has correct permissions for a Project Group, but simultaneously is part of another Team that does not have permissions for that Project Group. The Administrators Team's permissions should override permissions from any other Teams.

Steps to replicate:
Create a Team scoped to Project Group A only.

![projectgrouppermissions_1](https://cloud.githubusercontent.com/assets/20388190/23541813/7a7b28b4-0035-11e7-9f71-3dc15d2ca9d1.png)

Add an Admin user to that team (while that User is still in Administrators Team).
The Admin user's permissions to any Project Group other than Group A are affected.

![projectgrouppermissions_2](https://cloud.githubusercontent.com/assets/20388190/23541845/a05997d2-0035-11e7-8c36-c8f4781792b5.png)

The workaround is for the Admin user to only be within the Administrators Team.

Source: http://help.octopusdeploy.com/discussions/problems/51870

**Comment by matt-richardson** [comment] 2017-03-14 03:00
Closing as duplicate of https://github.com/OctopusDeploy/Issues/issues/3284 (even though this ticket was older). Work was done against the other ticket.

**Closed by matt-richardson** 2017-03-14 03:00 UTC
Labels: area/modelling, bug
