### ISSUE TITLE
Teams assigned to a Subscription aren't cleaned up when the Team is deleted.

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6684] opened 2020-12-03 11:31 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a team that is assigned to a subscription is deleted, it isn't removed from the subscription, instead, a Missing Resource value is left behind.

## What I expected to happen

The Team should be removed from any linked Subscriptions on deletion.

## Steps to reproduce

1. Create a Subscription
2. Assign a Team to the Subscription Email notification field
3. Delete the Team
4. Check the Subscription Email notification field and see a Missing Resource entry

### Screen capture

![image](https://user-images.githubusercontent.com/20085569/101007599-6226bf00-3559-11eb-837f-86b65d8ca9cb.png)

## Affected versions

**Octopus Server:** 2020.5.0

## Workarounds

The missing resource entry can be manually removed from the Subscription in the UI.
The presence of the deleted team shouldn't interfere with the running of the Subscription.

## Links

https://help.octopus.com/t/removing-a-team-doesnt-remove-it-from-subscriptions/26038

**Comment by mcasperson** [comment] 2020-12-07 18:50
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by mcasperson** [comment] 2020-12-07 18:51
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent team deletion when in use in a subscription](https://trello.com/c/Ck2z1L3a/4021-prevent-team-deletion-when-in-use-in-a-subscription)

**Comment by matt-richardson** [comment] 2020-12-07 22:32
Duplicate of of https://github.com/OctopusDeploy/Issues/issues/5301.

**Closed by matt-richardson** 2020-12-07 22:32 UTC
Labels: kind/bug, product/noqrfcapacity
