### ISSUE TITLE
CaC Sequence contains no matching element

### ISSUE THREAD

**Issue by domrichardson** [OctopusDeploy/Issues#7667] opened 2022-07-15 07:33 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Single Customer

### Version

2022.2.6971

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using the `Deploy Amazon ECS Service` step and setting the container details -> environment variables in a CaC enabled project results in the error: `Sequence contains no matching element`

Project becomes blocked and can only be fixed by removing the entry in the OCL file.

### Reproduction

* Create a new CaC Project
* Add the step `Deploy Amazon ECS Service`
* Fill in the required and container details ( without environment variables)
* Commit changes and reload page.
* Add environment variables
* Commit and reload page.

### More Information

[Internal Ticket](https://octopus.zendesk.com/agent/tickets/92909)

**Comment by YuKitsune** [comment] 2022-08-02 06:55
Looks like a duplicate of OctopusDeploy/Issues#7648
The fix should be available in `2022.3.4289` onwards.

I couldn't reproduce this exact issue on the latest build, though I came across a separate, [unrelated feeds issue](https://github.com/OctopusDeploy/Issues/issues/7700).

Closing for now, but please re-open if the issue is still present after `2022.3.4289`.

**Closed by YuKitsune** 2022-08-02 06:55 UTC
Labels: kind/bug, priority/p2, team/config-as-code
