### ISSUE TITLE
Users can't sign in when maintenance mode is enabled

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Issues#2925] opened 2016-11-17 15:34 UTC
In maintenance mode we prevent users being able to edit any documents. When 3.5 was introduced, I'm guessing that when users first sign in, we attempt to edit something. This results in the user not being able to sign in when maintenance mode is active before upgrading to 3.5.1. 

Sources:

http://help.octopusdeploy.com/discussions/problems/48995
http://help.octopusdeploy.com/discussions/problems/48801

**Comment by vanessalove** [comment] 2016-11-22 21:59
Closing - duplicate of https://github.com/OctopusDeploy/Issues/issues/2935

**Closed by vanessalove** 2016-11-22 21:59 UTC
Labels: bug
