### ISSUE TITLE
TypeError: Cannot read property 'Name' of undefined encountered on Overview screen when deleting previously used channel

### ISSUE THREAD

**Issue by reecewalsh** [OctopusDeploy/Issues#4152] opened 2018-01-09 04:30 UTC
**Octopus Version:**

Tested and Replicated on Octopus 4.1.6

**Issue:**

An unhandled JavaScript error is encountered on the project overview screen when a historical deployment present on the overview screen has a previously associated channel that was deleted and the project currently has more than 1 channel.

**Replication Steps:**

1)  Create a new project

![image](https://user-images.githubusercontent.com/33012349/34704817-8862e13a-f547-11e7-91f2-4e1e8b14f762.png)

2)  Create a secondary channel alongside the default

![image](https://user-images.githubusercontent.com/33012349/34704833-b8edb96a-f547-11e7-8213-bec538a86ab5.png)

3)  Create a release using the secondary channel created.

![image](https://user-images.githubusercontent.com/33012349/34704857-e10c4c04-f547-11e7-964e-e99f7fcbf9a7.png)

4)  Deploy the Release

![image](https://user-images.githubusercontent.com/33012349/34704872-00cb17c8-f548-11e7-8612-b3b54f639708.png)

5) Change the channel associated with the previously created release.

![image](https://user-images.githubusercontent.com/33012349/34704895-3e366ebe-f548-11e7-81f1-f539484f8db3.png)

6) Delete the existing channel that was originally used for the Release/Deployment.

![image](https://user-images.githubusercontent.com/33012349/34704909-5b39568e-f548-11e7-8234-1ace144d9451.png)

7) Navigate to the Project Overview screen - no issue is experienced at this stage.

![image](https://user-images.githubusercontent.com/33012349/34704949-9547065a-f548-11e7-935b-d558292e7654.png)

8) Add a Channel to the Project so that there is now more than 1 channel.

![image](https://user-images.githubusercontent.com/33012349/34705028-12304f64-f549-11e7-97c4-988e4cbcf4ea.png)

9) Navigate back to the Project Overview screen - this is when the error is encountered. 

![image](https://user-images.githubusercontent.com/33012349/34705046-2f7a00b0-f549-11e7-8437-94cddaf39c20.png)

**Full Exception:**

Attached is the Full Error Log
[Overview Error.txt](https://github.com/OctopusDeploy/Issues/files/1613844/Overview.Error.txt)

Octopus v4.1.6
TypeError: Cannot read property 'Name' of undefined
    at t.renderTaskStatusCell (http://localhost/main.7aaae1e862ed0dbbc376.hashedasset.js:1:830719)
    at t.render (http://localhost/main.7aaae1e862ed0dbbc376.hashedasset.js:1:828675)
    at u (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:336789)
    at beginWork (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:338289)
    at i (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:350581)
    at u (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:351097)
    at c (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:351572)
    at m (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:353594)
    at h (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:353103)
    at Object.enqueueSetState (http://localhost/react.44c43694a8ff6197bd86.hashedasset.js:1:334370)

**Workaround/Solution:** 

Creating a new release and completing the deployment process will return the Overview screen back to normal functionality.

**Source:**

https://help.octopusdeploy.com/discussions/problems/67660

**Comment by johnsimons** [comment] 2018-02-21 06:56
This seems to be duplicate of https://github.com/OctopusDeploy/Issues/issues/4262

**Closed by johnsimons** 2018-02-21 06:56 UTC
Labels: area/modelling, bug, duplicate
