### ISSUE TITLE
Cannot delete deployment if team is scoped to specific environments

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#3603] opened 2017-06-28 16:43 UTC
Unless the team is scoped to all environments, the API returns 

```
"You do not have permission to perform this action. Please contact your Octopus administrator. Missing permission: DeploymentDelete"
```

The expected behavior is that if the team is only scoped to `Dev`, that user should be able to delete deployments to `Dev` from the API.

Octopus: `3.14.1`
Source: http://help.octopusdeploy.com/discussions/problems/55494

**Comment by NickJosevski** [comment] 2019-02-19 10:11
Closing as cannot reproduce using customers permissions and setup. It appears to work

**Closed by NickJosevski** 2019-02-19 10:11 UTC
Labels: area/modelling
