### ISSUE TITLE
Viewing step with a variable run condition shows "You have unsaved changes" and prompts user to save when leaving page.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#3662] opened 2017-07-13 01:37 UTC
Any step that has a run condition variable defaults to "You have unsaved changes" regardless of changing anything.

Steps to replicate:
1. Create any step.
2. Set run condition variable to anything. Save & exit step.
3. Re-opening the step shows "You have unsaved changes" in the top right and prompts you as you leave.

Changing run condition to "Always run" without removing the data from the variable run condition continues to cause this issue.

Source: http://help.octopusdeploy.com/discussions/problems/55877

**Comment by droyad** [comment] 2017-09-27 10:20
Duplicate of #3349

**Comment by pawelpabich** [comment] 2017-11-22 03:48
This is fixed in Octopus 4.0

**Closed by pawelpabich** 2017-11-22 03:48 UTC
Labels: area/modelling, bug
