### ISSUE TITLE
Accessing branches with / (forward slash) in the name throws error when using IIS as a reverse proxy for Octopus Server

### ISSUE THREAD

**Issue by gupta-kartik** [OctopusDeploy/Issues#7593] opened 2022-06-07 07:10 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Atleast one report of a customer running into this. Workaround exists.

### Version

Reproduced on 2022.1.2584

### What happened?

While using IIS as a reverse proxy for Octopus Server, an error `There was an error accessing version control` is seen while accessing configuration-as-code projects with branches that include a `/` forward slash in the name (e.g `feature/my-feature`).

![image](https://user-images.githubusercontent.com/4622084/172314071-f396dff3-b130-49ba-b95d-f13cb6d7f039.png)

### Reproduction

1. Run an Octopus Server instance
2. Create a new project with config as code enabled. This requires having write access to a git remote e.g. github.com/user/repo-name.git
3. Add a branch to the remote with a `/` in the name. E.g. `feature/my-feature`
4. Verify you can see the branch in the Octopus UI by going to your Project > Deployments > Process and clicking the branch selector
5. Follow the steps here https://octopus.com/docs/security/exposing-octopus/use-iis-as-reverse-proxy to use IIS as a reverse proxy for your Octopus Deploy instance (NB: You can skip the steps requiring SSL setup for a quick reproduction)
6. Navigate to the endpoint specified in your IIS config, usually http://localhost:80
7. Navigate to the Deployment Process screen in the Octopus UI (proxied) and select the `feature/my-feature` branch
8. See error

### Error and Stacktrace

```shell
2022-06-07 11:53:47.1868   8240      4  INFO  "HTTP" "GET" to "localhost:8065""/api/Spaces-1/projects/Projects-1/git/branches/feature/net6-upgrade" completed with 404 in 00:00:00.0384568 (038ms) by "admin"
2022-06-07 11:53:49.2199   8240     14 ERROR  Unhandled error on request: "We received a request for a version-controlled resource on a non-version control route. Please use projects/{projectId}/{gitRef}/summary"
System.InvalidOperationException: We received a request for a version-controlled resource on a non-version control route. Please use projects/{projectId}/{gitRef}/summary
   at Octopus.Server.Web.Middleware.ActionFilters.ProjectScopeResourceFilter.GetProjectPath(Project project, ResourceExecutingContext context) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\ActionFilters\ProjectScopeResourceFilter.cs:line 114
   at Octopus.Server.Web.Middleware.ActionFilters.ProjectScopeResourceFilter.TryExtractProjectRouteScope(ResourceExecutingContext context, CancellationToken cancellationToken) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\ActionFilters\ProjectScopeResourceFilter.cs:line 97
   at Octopus.Server.Web.Middleware.ActionFilters.ProjectScopeResourceFilter.ApplyToScope(ResourceExecutingContext ctx, CancellationToken cancellationToken) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\ActionFilters\ProjectScopeResourceFilter.cs:line 55
   at Octopus.Server.Web.Middleware.ActionFilters.ProjectScopeResourceFilter.OnResourceExecutionAsync(ResourceExecutingContext context, ResourceExecutionDelegate next) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\ActionFilters\ProjectScopeResourceFilter.cs:line 47
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Infrastructure\Authentication\AuthorizationMiddlewareResultHandler.cs:line 50
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\UnitOfWorkMiddleware.cs:line 32
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\UnitOfWorkMiddleware.cs:line 45
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\OctopusClientOldVersionWarningMiddleware.cs:line 26
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\DynamicContentHeadersMiddleware.cs:line 48
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\MaintenanceModeMiddleware.cs:line 60
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 103
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, CorrelationId correlationId) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\OctopusAuthenticationMiddleware.cs:line 66
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\LegacyRequestLoggerMiddleware.cs:line 33
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\TelemetryMiddleware.cs:line 75
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in C:\dev\OctopusDeploy\source\Octopus.Server\Web\Middleware\ErrorHandlingMiddleware.cs:line 34
```

### More Information

Octopus encodes `/` in the path to `%2F` and sends this to the Server to the ASP.Net framework. IIS is eagerly decoding `%2F` back to `/` already.

### Workaround

The workaround involves configuring IIS to leave the encoded path param in the URL as is. (This builds upon the steps listed in https://octopus.com/docs/security/exposing-octopus/use-iis-as-reverse-proxy)  One way to do this is:

1. Open IIS Manager
2. For your reverse proxy website set up earlier, navigate to URL Rewrite settings by double clicking
3. Double Click the `ReverseProxyInboundRule1` created earlier to edit it
4. Scroll to the bottom to the "Action" area and select `Rewrite` from the "action type" drop down
5. In the textbox under action properties, the rewrite URL should look like `{C:1}://localhost:8065{UNENCODED_URL}` where localhost:8065 is the port where my Octopus Server is running
6. Uncheck the "Append Query string" checkbox
7. Click "Apply" to save the changes to the Rule
8. Navigate back to the IIS reverse proxy website screen and double click on Configuration editor
9. Change tje section to system.webServer/rewrite/rules and change `useOriginalURLEncoding` to `False`

By the end your IIS web.config for your website (default can be found C:/inetpub/wwwroot/web.config) should look something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules useOriginalURLEncoding="false">
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions>
                        <add input="{CACHE_URL}" pattern="^(https?)://" />
                    </conditions>
                    <action type="Rewrite" url="{C:1}://localhost:8065{UNENCODED_URL}" appendQueryString="false" />
                    <serverVariables>
                    </serverVariables>
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

IIS should now stop decoding API requests to Octopus and you should be able to view branches with `/` in the UI.

![image](https://user-images.githubusercontent.com/4622084/172318686-24a71c07-c8ed-49c3-ba7a-4448c16dad45.png)

**Comment by gupta-kartik** [comment] 2022-06-07 07:15
Customer report of problem (public) https://help.octopus.com/t/bitbucket-feature-branches-and-config-as-code/27979

**Comment by YuKitsune** [comment] 2022-06-10 05:58
Closing this since this issue is caused by external software, and a workaround exists.

**Closed by YuKitsune** 2022-06-10 05:58 UTC
Labels: kind/bug, priority/low, state/triage, team/config-as-code

**Comment by fantom732315** [comment] 2024-02-12 07:44
I have the same problem with Octopus in Azure AppServices and this workaround doesn't work(
