### ISSUE TITLE
Long variable values alter All Variables page layout

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6590] opened 2020-09-23 13:53 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a variable has a long value added, when viewing All Variables page the layout of the columns will extend too much.

## What I expected to happen

The layout should remain as is and the long variable becomes truncated

## Steps to reproduce

1. Add a long value to a project variable
2. Navigate to All Variables

### Screen capture

![image](https://user-images.githubusercontent.com/20085569/94021871-68a3f800-fdac-11ea-9bee-48cbc9ac03b2.png)

## Affected versions

**Octopus Server:**2020.3.6+

## Workarounds

None

## Links

[Internal Link](https://secure.helpscout.net/conversation/1289967798/70904?folderId=3252735)

**Comment by calverp** [comment] 2020-09-23 13:53
![](https://github.trello.services/images/mini-trello-icon.png) [Long variable values alter All Variables page layout](https://trello.com/c/dk51KhKc/3759-long-variable-values-alter-all-variables-page-layout)

**Comment by mcasperson** [comment] 2020-09-29 01:15
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by matt-richardson** [comment] 2020-11-05 22:47
Closing as a duplicate of https://github.com/OctopusDeploy/Issues/issues/5706

**Closed by matt-richardson** 2020-11-05 22:47 UTC
Labels: kind/bug, product/noqrfcapacity
