### ISSUE TITLE
Deploy Kubernetes ingress resource step template throws error when selecting "Octopus Certificate

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#6781] opened 2021-03-02 20:48 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [ ] I have verified the problem exists in the latest version
- [ ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ ] I have written a descriptive issue title
- [ ] I have linked the original source of this report
- [ ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

### Screen capture

![Screenshot](https://www.fillmurray.com/640/360)

### Log excerpt

```
Insert your log excerpt here.
```

## Affected versions

**Octopus Server:**

**Comment by kengel100** [comment] 2021-03-22 01:20
Duplicate of #6782

**Closed by kengel100** 2021-03-22 01:20 UTC
Labels: kind/bug
