### ISSUE TITLE
Sub menus of menu “More” don’t work within the Octopus UI

### ISSUE THREAD

**Issue by Clare-Octopus** [OctopusDeploy/Issues#7312] opened 2022-01-13 16:51 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Cosmetic issue, not blocking customers from deploying.

### Version

2021.3.8275

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Go to a project and go to the overview or releases page, if you resize the browser window in the Octopus UI to make sure the 'More' menu is displayed and click on it you will see the drop-down menu. However, the UI will not show you any sub-menus of items within the more menu (such as 'operations' or 'variables')

See video in the reproduction section for more information.

I have reproduced this with the latest firefox and chrome browsers in a hyper-v environment.

![image](https://user-images.githubusercontent.com/92790462/149373101-222ffea4-2215-4d4a-a151-0ded9e3c0b68.png)

### Reproduction

1 - Open up the Octopus UI 
2 - Navigate to a project and click on 'Releases' (this also happens in the overview page)
3- Resize the screen until you see the 'More' menu on the top.
4- Click on the 'More' menu item to bring up the drop-down menu.
5- Hover over a menu with a triangle next to it (to indicate a sub-menu is present).
6 - Notice no submenu appears, if you click on the menu item the sub-menu still does not appear and you get the console stack trace errors as shown below
7- Resize the window until the more menu disappears and you see the variables menu at the top again.
8 - Notice the submenu now appears.

If you resize the window again to show the 'more' menu the same happens above so it does not reset if you manipulate the window size.

![ee85f197e8e13d576390f158b70c6fcc1b08a069](https://user-images.githubusercontent.com/92790462/149372112-facb685e-cbd4-45e0-9ab8-e1e41b0fb283.gif)

### Error and Stacktrace

```shell
logger.ts:10 Creating Octopus client for endpoint: http://localhost/
importAsync.tsx:31 Loading dynamic chunk: e=>e.ProjectRoutes
importAsync.tsx:31 Loading dynamic chunk: e=>e.LibraryRoutes
importAsync.tsx:31 Loading dynamic chunk: e=>e.InfrastructureRoutes
importAsync.tsx:31 Loading dynamic chunk: e=>e.TenantsRoutes
importAsync.tsx:31 Loading dynamic chunk: e=>e.ConfigurationRoutes
importAsync.tsx:31 Loading dynamic chunk: e=>e.TaskRoutes
logger.ts:10 Progress:  Checking your credentials. Please wait...
importAsync.tsx:38 Loaded dynamic chunk: e=>e.ProjectRoutes
importAsync.tsx:38 Loaded dynamic chunk: e=>e.LibraryRoutes
importAsync.tsx:38 Loaded dynamic chunk: e=>e.InfrastructureRoutes
importAsync.tsx:38 Loaded dynamic chunk: e=>e.TenantsRoutes
importAsync.tsx:38 Loaded dynamic chunk: e=>e.ConfigurationRoutes
importAsync.tsx:38 Loaded dynamic chunk: e=>e.TaskRoutes
useMiniProfilerTrackedRequests.ts:39 []
logger.ts:10 User already authenticated
logger.ts:10 Starting session for octoadmin@octopus_domain.com user.
logger.ts:10 User already authenticated
logger.ts:10 Starting session for octoadmin@octopus_domain.com user.
react-dom.production.min.js:209 Error: Invariant failed
    at r (tiny-invariant.esm.js:8:15)
    at react-router.js:695:142
    at wl (react-dom.production.min.js:268:137)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
nl @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
hi @ react-dom.production.min.js:131
ll @ react-dom.production.min.js:212
gs @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
vs @ react-dom.production.min.js:248
rs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
react-dom.production.min.js:209 Error: Invariant failed
    at r (tiny-invariant.esm.js:8:15)
    at react-router.js:695:142
    at wl (react-dom.production.min.js:268:137)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
nl @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
hi @ react-dom.production.min.js:131
ll @ react-dom.production.min.js:212
gs @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
vs @ react-dom.production.min.js:248
rs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
react-dom.production.min.js:209 Error: Invariant failed
    at r (tiny-invariant.esm.js:8:15)
    at react-router.js:695:142
    at wl (react-dom.production.min.js:268:137)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
nl @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
hi @ react-dom.production.min.js:131
ll @ react-dom.production.min.js:212
gs @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
vs @ react-dom.production.min.js:248
rs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
react-dom.production.min.js:209 Error: Invariant failed
    at r (tiny-invariant.esm.js:8:15)
    at react-router.js:695:142
    at wl (react-dom.production.min.js:268:137)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
nl @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
hi @ react-dom.production.min.js:131
ll @ react-dom.production.min.js:212
gs @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
vs @ react-dom.production.min.js:248
rs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
react-dom.production.min.js:209 Error: Invariant failed
    at r (tiny-invariant.esm.js:8:15)
    at react-router.js:695:142
    at wl (react-dom.production.min.js:268:137)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
nl @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
hi @ react-dom.production.min.js:131
ll @ react-dom.production.min.js:212
gs @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
vs @ react-dom.production.min.js:248
rs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
react-dom.production.min.js:209 Error: Invariant failed
    at r (tiny-invariant.esm.js:8:15)
    at react-router.js:695:142
    at wl (react-dom.production.min.js:268:137)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
nl @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
hi @ react-dom.production.min.js:131
ll @ react-dom.production.min.js:212
gs @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
vs @ react-dom.production.min.js:248
rs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
react-dom.production.min.js:123 Uncaught Error: Invariant failed
    at r (tiny-invariant.esm.js:8:15)
    at react-router.js:695:142
    at wl (react-dom.production.min.js:268:137)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
r @ tiny-invariant.esm.js:8
(anonymous) @ react-router.js:695
wl @ react-dom.production.min.js:268
fs @ react-dom.production.min.js:246
ds @ react-dom.production.min.js:246
rs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
ne @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
```

### More Information

Discourse ticket - https://help.octopus.com/t/sub-menus-of-menu-more-dont-work/27559 

### Workaround

No workaround exists, the user just has to resize the browser menu to ensure the 'More' menu isn't shown and the 'Variables' and 'Operations' menus are shown on the top or the left of the screen.

**Comment by KennethBates** [comment] 2022-01-13 23:06
Duplicate of https://github.com/OctopusDeploy/Issues/issues/7272

**Closed** 2022-01-13 23:09 UTC
Labels: kind/bug, state/triage, team/fire-and-motion

**Comment by Clare-Octopus** [comment] 2022-01-14 09:06
Didn't realise this was a duplicate! Thank you for looking into this I will inform the customer a fix is available in the latest version when it is out for public release.
