### ISSUE TITLE
Error when disabling automatic release creation

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#5954] opened 2019-11-01 09:53 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When disabling an Automatic Release Creation trigger, an error message will be displayed. The trigger is disabled successfully though.

## What I expected to happen

No error message to appear.

## Steps to reproduce

1. Create an Automatic Release Creation trigger on any project
2. Disable the trigger

### Log exerpt

```
An unexpected error occurred in Octopus v2019.10.1: Object doesn't support property or method 'dialogOnClose'


•TypeError: Object doesn't support property or method 'dialogOnClose' 
•onClose (http://localhost:82/main.07d0dec3722e48078b41.hashedasset.js:1:665207) 
•Anonymous function (http://localhost:82/main.07d0dec3722e48078b41.hashedasset.js:1:667627) 
•Anonymous function (http://localhost:82/main.07d0dec3722e48078b41.hashedasset.js:1:666998) 
•Anonymous function (http://localhost:82/main.07d0dec3722e48078b41.hashedasset.js:1:666311) 
•s (http://localhost:82/main.07d0dec3722e48078b41.hashedasset.js:1:665849) 
•Anonymous function (http://localhost:82/vendor.b7f120073fa9708a7687.hashedasset.js:36:2814) 
•z (http://localhost:82/vendor.b7f120073fa9708a7687.hashedasset.js:36:2790) 
•j (http://localhost:82/vendor.b7f120073fa9708a7687.hashedasset.js:36:2635) 
•g (http://localhost:82/vendor.b7f120073fa9708a7687.hashedasset.js:36:663)

```

## Affected versions

**Octopus Server:** 2019.10.2

## Workarounds

No workaround required as the disable does succeed.

## Links

[Internal Link](https://secure.helpscout.net/conversation/995358636/52525/)

**Comment by matt-richardson** [comment] 2019-11-01 19:45
Duplicate of https://github.com/OctopusDeploy/Issues/issues/5948.
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/4672 - will be in `2019.10.3`

**Closed by matt-richardson** 2019-11-01 19:45 UTC
Labels: kind/bug
