### ISSUE TITLE
Azure Deployments don't work with PS 2

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#2761] opened 2016-09-15 04:49 UTC
Azure.Calamari uses a `Path.Combine` overload in it's scripts that became available in .NET 4.0. PS 2 uses .NET 2 or 3.5 by default, so the script fails.

One of the scripts with this issue:
https://github.com/OctopusDeploy/Calamari/blob/f17c1f10fc95f7406bcd7f4b09b332fb64734b7d/source/Calamari.Azure/Scripts/AzureContext.ps1

Work around is to install PS 3+ or run .NET 4.0 by default: http://www.adminarsenal.com/admin-arsenal-blog/powershell-running-net-4-with-powershell-v2/

`Azure API Test` build has been set to not run on the Win2008 agent.

**Comment by michaelnoonan** [comment] 2016-10-14 02:07
Looks like a duplicate of https://github.com/OctopusDeploy/Issues/issues/2823

**Closed by michaelnoonan** 2016-10-14 02:07 UTC
