### ISSUE TITLE
Docker image used as step exaction container acquired multiple times

### ISSUE THREAD

**Issue by APErebus** [OctopusDeploy/Issues#7355] opened 2022-02-04 06:11 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Slows down every deployment by 3+ extra minutes

### Version

2021.3

### What happened?

When you use a docker container as a step execution container, the docker image is "acquired" once per step, even if it's the same image being used.

![image](https://user-images.githubusercontent.com/332730/152481056-26b85f28-b8f4-4215-b18b-2b5367a057d7.png)

This means for deployments with lots of steps with execution containers, you can waste minutes at the start acquiring the same package unnecessarily

### Reproduction

see https://deploy.octopus.app/app#/Spaces-443/projects/octofront/deployments/releases/8.600.1/deployments/Deployments-158133

**Comment by zentron** [comment] 2022-02-06 23:40
Thanks @APErebus 
Closing as Duplicate of https://github.com/OctopusDeploy/Issues/issues/7018

**Closed by zentron** 2022-02-06 23:40 UTC
Labels: kind/bug, state/triage, team/fire-and-motion
