### ISSUE TITLE
Usability of tenant variables page with a lot of variables

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3813] opened 2017-09-21 02:49 UTC
If you have a large number of project variables (100+) that need to be defined for each tenant, this *Tenants > [Tenant Name] > Variables* page becomes massive. It's not very user-friendly in this scenario. A filter or search option on this page could be a good addition to address the usability of this page.

Possible workaround to having to manage such a long list of variables: reduce the number of needed variables by managing them as JSON or XML, and store the entire set for each tenant as a single variable. This would resolve the large number of variables, but it depends on whether you can modify the process to work with this.

Source: https://help.octopusdeploy.com/discussions/questions/13195-conversion-from-single-to-multi-tenant

**Comment by MJRichardson** [comment] 2017-10-05 01:17
Ensure tenant variables page is usable for large numbers in 4.0.

**Comment by droyad** [comment] 2017-10-31 06:00
v4 card https://trello.com/c/rS53KzQR/589-usability-of-tenant-variables-page-with-a-lot-of-variables

**Comment by pawelpabich** [comment] 2017-11-09 07:50
This is not going to be done as part of v4. Correct if I'm wrong @MJRichardson.

**Comment by jess-ross** [comment] 2018-01-10 05:22
![](https://github.trello.services/images/mini-trello-icon.png) [Usability of tenant variables page with a lot of variables](https://trello.com/c/cxADcYsH/16-usability-of-tenant-variables-page-with-a-lot-of-variables)

**Comment by egorpavlikhin** [comment] 2018-03-22 12:56
The issue is not just in a large number of variables but in any amount. Everything on the page is large, except the input fields. Which only support 60 symbols per variable. An average connection string can easily be 100+ characters.

![image](https://user-images.githubusercontent.com/1160707/37771647-4f2a8514-2de9-11e8-8ca4-43704f88f824.png)

Consider how AutoStoreTerminal:Guid is repeated 3 times for no good reason.

An option for compact UI would also be helpful.

Right now variables in Octopus do not support anything but the simplest scenarios.

**Comment by zentron** [comment] 2022-02-22 05:57
Closing well-known ticket to be addressed as broader tenant scaling problems

**Closed by zentron** 2022-02-22 05:57 UTC
Labels: kind/enhancement, feature/usability, feature/tenants, feature/variables, size/large, area/core, team/fire-and-motion
