### ISSUE TITLE
Newly added environment does not show on dashboard

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#5067] opened 2018-11-08 01:22 UTC
- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Newly added environment does not show on dashboard until process restart or a lifecycle is updated (updating other documents possibly trigger the dashboard to reload to show the correct data)

## Steps to reproduce
1. Browse to the dashboard
2. Then add a new environment from the instructure page
3. Browse to the dashboard again
4. Newly added environment does not show
5. Browse to the default lifecycle page and update the description
6. Browse back to the dashboard page, newly added environment is now shown

## Links

https://secure.helpscout.net/conversation/698574938

**Comment by droyad** [comment] 2019-01-31 01:47
Duplicate of #4912

**Closed by droyad** 2019-01-31 01:47 UTC
Labels: area/modelling, kind/bug
