### ISSUE TITLE
Dashboard does not show the latest release

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#3685] opened 2017-07-21 06:03 UTC
Octopus 3.15.7

Currently the dashboard page does not show the most recent release deployed to an environment. Here's the project overview page, which correctly shows release `2.7-beta14` deployed to `Tenant 1`

![project_overview](https://user-images.githubusercontent.com/20388190/28450981-131dc82c-6e2e-11e7-8e56-e9bec04bcf93.png)

In the dashboard page, this project shows the `2.7-beta9` release version as most recent in the `Development` environment.

![dashboard](https://user-images.githubusercontent.com/20388190/28450992-198d3a8a-6e2e-11e7-8d42-60055849c85d.png)

Steps to reproduce:

1) Create two tenants
2) Create two releases (this example uses `-beta9` then `-beta14`)
3) Deploy the first release first to one tenant, and the later release version to the next tenant
4) In the `Dashboard` page, the earlier release is displayed in the environment column

The expected behavior is that the `2.7-beta14` release version should be displayed in the dashboard in the Development environment, as it's the later release version, and was the last deployed.

Related issue: https://github.com/OctopusDeploy/Issues/issues/3325

Source: http://help.octopusdeploy.com/discussions/problems/56100

**Comment by TomPeters** [comment] 2017-07-26 03:18
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard does not show the latest release](https://trello.com/c/uV76HlvO/694-dashboard-does-not-show-the-latest-release)

**Comment by droyad** [comment] 2017-09-27 09:54
This is due to alphabetical instead of SemVer sorting

**Comment by johnsimons** [comment] 2018-01-15 04:41
As pointed out by @droyad the issue is that the dashboard uses semver for sorting and in this case `beta9 > beta14`. see https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#semantic-versioning

To correct this issue the release version should be padded with 0s, so that, eg:
- beta0009
- beta0014
This was the sorting is will work correctly.

On the other hand, it could be that user may want to see the latest release based on date released, I have added a comment to https://github.com/OctopusDeploy/Issues/issues/3419#issuecomment-357581282

So based on all this I am closing this issue, feel free to reopen if you disagree with the assessment.

**Closed by johnsimons** 2018-01-15 04:41 UTC
Labels: area/modelling, bug

**Comment by droyad** [comment] 2018-01-15 06:14
I think we should do the right thing and sort by SemVer. While this may be difficult in SQL, we could pre-calculate the order.

**Comment by johnsimons** [comment] 2018-01-15 06:44
@droyad according to 
 https://github.com/OctopusDeploy/OctopusDeploy/blob/cdf9dd7df9b6cb92c07b3a562f630baa95df3db8/source/Octopus.Server/Web/Api/Components/DashboardBuilder.cs#L83-L97, we are using semver to sort, but it seems our implementation defaults to string comparison https://github.com/OctopusDeploy/CoreVersioning/blob/0337dc31325350a817af617b2f38798501bf55c6/source/Octopus.Server.Core.Versioning/Octopus/Core/Resources/Versioning/Semver/VersionComparer.cs#L303.

Also I think the same issue exists in the nuget implementation.

So I am not sure what you suggesting ?

**Comment by droyad** [comment] 2018-01-15 10:24
Ah, my bad, I misread your answer. "To correct this issue" refers to the OP's problem, not an issue within Octopus. The sorting is working correctly. Another solution is to use `beta.14`.
