### ISSUE TITLE
Editing K8 YAML in CaC projects 500 Error

### ISSUE THREAD

**Issue by domrichardson** [OctopusDeploy/Issues#7665] opened 2022-07-14 09:05 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Single ticket but able to reproduce

### Version

2022.2.6971

### What happened?

With a CaC enabled project when editing a Kubernetes step YAML then commits the changes, running a deployment after committing causes a 500 Error. 

This fails to search/download the container from an external feed.

Looking at the commit on the OCL file I can see the feed is empty compared to the original file.

### Reproduction

Steps to reproduce:

* Create a project with version control setup
* Add a Kubernetes Deploy Container step
* Commit 
* Edit the YAML and change the container
* Commit
* Run Deployment

### Workaround

After editing the YAML, remove the container from the UI, then re-add the container and commit changes.

**Comment by YuKitsune** [comment] 2022-08-03 05:10
Hi @domrichardson 
I'm having some trouble getting a reliable repro, though I did manage to get a similar error on the "Create Release" page.
Is the error showing up on the Create Release page, or during a deployment?

**Comment by StephenHeise** [comment] 2022-08-09 02:41
Hi @domrichardson 
I'm also having some trouble reproducing this issue. It would be helpful to have a bit more details to try and track down what might be going on there.
1. "running a deployment" - just to clarify, do mean you create a new release and the error occurs when the new release is deployed? If not, at exactly which point does the error occur?
2. "500 Error" what API call is that? What is in the body of the response? What are in the server logs at this point? Are there any errors in the browser console?
3. "change the container" What exactly do mean by this? I assume you mean on the Kubernetes Deploy Container step, Deployment section, Containers. Are you removing an existing one and adding a new one or modifying an existing one? If modifying, exactly which property or properties are you changing? How many containers have you specified?

**Comment by domrichardson** [comment] 2022-08-09 10:56
@StephenHeise @YuKitsune To clarify, Add a Kubernetes Deploy Container step and set the container to nginx or something. then commit the initial deployment process. refresh the page to clear any cache. Then edit the step YAML and change container to ubuntu or something else, and commit that change. then create a new release and the 500 error should show.

[Internal Ticket](https://octopus.zendesk.com/agent/tickets/92816)

**Comment by YuKitsune** [comment] 2022-08-29 23:55
Thanks @domrichardson 
I've taken a look at the ticket, and it looks like this is actually related to OctopusDeploy/Issues#7626.
I've spent some time today trying to get a repro, and I still haven't found any luck. I'm gonna close this issue for now.

**Closed by YuKitsune** 2022-08-29 23:55 UTC
Labels: kind/bug, priority/p2, team/config-as-code
