### ISSUE TITLE
SQL Server networking issue caused Octopus windows service stopped

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#4027] opened 2017-12-04 03:44 UTC
## Issue
During `HeartbeatAndUpdateRankIfRequired` from `Octopus.Server.Schedules.Scheduler`, the `Heartbeat` method will connect to database to do the `UpdateLastSeen`, exception will be thrown if the SQL Server is down, the process will then try to connect to the database in the catch block to `GetCurrentNode`, as the SQL Server is still down, another exception will be thrown and bubble up which causes the Octopus windows service stopped 

Logs files are available from this ticket https://help.octopusdeploy.com/discussions/problems/64558

**Comment by droyad** [comment] 2017-12-06 22:11
This is a duplicate of #4012

**Closed** 2017-12-06 22:54 UTC
Labels: bug, priority
