### ISSUE TITLE
Updating variables in a release is not working

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1749] opened 2015-07-23 04:29 UTC
The following error is logged in the browser console when clicking the `Update Variables` button:

![image](https://cloud.githubusercontent.com/assets/1035315/8843094/1506ebbc-3147-11e5-860b-d15c2e835c94.png)

**Comment by michaelnoonan** [comment] 2015-07-23 04:31
I've been able to reproduce this.

**Comment by zentron** [comment] 2015-07-24 04:01
Item has since been fixed in earlier build.

**Closed by zentron** 2015-07-24 04:01 UTC
Labels: bug, in progress
