### ISSUE TITLE
Pushing a NuGet package from OSX fails with "The uploaded file isn't a valid NuGet package."

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#1491] opened 2015-02-24 05:58 UTC
The exception that is thrown when uploading the package:

```
at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOBlockManager.LoadEndOfCentralDirectoryBlock()
   at MS.Internal.IO.Zip.ZipArchive.OpenOnFile(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
   at NuGet.Lucene.FastZipPackage.Open(String originalFilePath, IHashProvider hashProvider)
   at Octopus.Server.Web.Api.NuGet.NuGetPackagePushActionBase`1.Execute() in 
c:\Code\GitHub\OctopusDeploy_2_6\source\Octopus.Server\Web\Api\NuGet\NuGetPackagePushActionBase.cs:line 65
```

The content lengths of the uploaded file from OSX and Windows differ by 1:

```
OSX
Length    17514296    long

Windows
Length    17514297    long
```

And trying to open the package pushed from OSX in NuGet Package Explorer displays the below error:

![image](https://cloud.githubusercontent.com/assets/1035315/6344014/cedd0fbe-bc3d-11e4-80b4-60d24692f843.png)

Pushing the same package from a Windows box to the built-in feed works just fine.

Source: http://help.octopusdeploy.com/discussions/problems/30658

**Comment by graemechristie** [comment] 2015-03-19 03:06
I'm seeing the same thing here, pushing from OSX with the latest Nuget.exe/mono. Is there a workaround for this ?

**Comment by mrtimp** [comment] 2015-07-27 01:45
I can confirm that I'm having the same issue from a CentOS 6 x86_64 guest using mono version 3.10.0 or 4.0.2 and NuGet version 2.8.60717.93.

If I manually upload this from my OSX desktop using Chrome the upload is fine, it only seems to be an issue uploading it via NuGet.

**Comment by PaulStovell** [comment] 2015-08-19 06:03
Thanks for getting in touch. You've raised a valid issue, but unfortunately we don't think we will have time to fix this in the near future due to other priorities. We've decided to close it for now. For more information, please see this page:
http://octopusdeploy.com/roadmap/why-was-this-closed

**Closed** 2015-08-19 06:03 UTC
Labels: bug
