### ISSUE TITLE
Migration tool: creating projects that cannot be accessed or even deleted

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1781] opened 2015-07-27 12:34 UTC
The migration tool is importing projects that have the FTP or Azure steps removed. But then you cannot view anything about the project, and can't even delete it. 
Can we a) stop the behavior when importing
and b) help the customers who have upgraded and are stuck with these tasks to see the other parts of the project (such as variables and steps) or even be able to delete it.

Se screenshot for behavior and customer experience in the first source:
https://secure.helpscout.net/conversation/107640759/367/
http://help.octopusdeploy.com/discussions/problems/36441

**Comment by IanMercer** [comment] 2015-07-27 16:15
b) moved to a separate issue: https://github.com/OctopusDeploy/Issues/issues/1784

**Comment by IanMercer** [comment] 2015-07-27 16:23
We could stop the behavior when importing by refusing to migrate. But currently, by design, we allow users to ignore the error message "Ftp package deployment steps are no longer supported, please remove them and create a new backup" and proceed because they may not have access to a 2.6 source to fix it.

**Comment by IanMercer** [comment] 2015-07-27 23:46
Fixed by OctopusDeploy/OctopusDeploy/pull/288

**Closed** 2015-07-27 23:47 UTC
Labels: bug, priority, ready
