### ISSUE TITLE
Sql Connection Leak Reported

### ISSUE THREAD

**Issue by robpearson** [OctopusDeploy/Issues#2348] opened 2016-02-04 11:25 UTC
Issue to investigate and profile sql connections usage with the latest Octopus release.  Issue was reported in 3.2.19 but a comment on #2197 stated they had a similar issue with 3.2.13.

Simple workaround is to restart the Octopus Server.

Source: http://help.octopusdeploy.com/discussions/problems/44290

**Comment by michaelnoonan** [comment] 2016-02-04 23:19
Could be related to https://github.com/OctopusDeploy/Issues/issues/2197

**Comment by robpearson** [comment] 2016-02-19 00:54
Customer was able to isolate the issue to a specific event ... Listening Tentacles that are not responding to the health check.

**Comment by roberto-mardeni** [comment] 2016-03-28 12:57
Any updates on this? it's been a while and we keep seen this issue happening in our side.

**Comment by antonvk** [comment] 2016-03-30 12:21
Hi,

We have also experienced this issue and restarting octopus to resolve the issue is getting a little much now. any news on when this will be fixed?

**Comment by droyad** [comment] 2016-06-17 05:39
Possibly related to https://github.com/OctopusDeploy/Issues/issues/2555. See if that resolved this issue.

**Comment by vanessalove** [comment] 2016-07-12 22:27
Will reopen if reported above version 3.3.18

**Closed** 2016-07-12 22:27 UTC
Labels: pending
