### ISSUE TITLE
Guided failure in a child project causes deployment failure

### ISSUE THREAD

**Issue by OctoStu** [OctopusDeploy/Issues#6658] opened 2020-11-04 11:53 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using deploy a release step with guided failure, if a step in the child project fails and is ignored, and then a second failure occurs, the parent project will fail despite the child project succeeding.

## What I expected to happen

Parent project should appear as success with warnings.

## Steps to reproduce

1. Create a project with two scripts steps that will fail
2. Create a second project with a deploy release step
3. Enable guided failure on the second project
4. Create release for both projects
5. Deploy the second project
6. Select ignore for the first and second failure
7. Check deployment of the second project, it'll be marked as failed

### Screen capture

![image](https://user-images.githubusercontent.com/71699621/98108364-bd4e8e80-1e93-11eb-89f0-78bcd82f91d1.png)

## Affected versions

**Octopus Server:** 2020.5.0

## Workarounds

The deployment does complete successfully; the UI shows as failed. To avoid confusion, you can manually change the parent deployment state from failed to success.

## Links

https://help.octopus.com/t/deployment-fails-after-manual-intervention-is-resolved-with-guidance-ignore/25909/2

**Comment by droyad** [comment] 2020-11-10 05:06
Possibly duplicate of  #6494

**Comment by kengel100** [comment] 2021-03-17 03:59
Closing this issue as a duplicate of [#6494](https://github.com/OctopusDeploy/Issues/issues/6494). Please subscribe to #6494 for updates.

**Closed by kengel100** 2021-03-17 03:59 UTC
Labels: area/core, closed/duplicate, feature/deployreleasestep, kind/bug
