### ISSUE TITLE
Helm external feeds with poorly formatted index.yaml (i.e. not semver compliant) don't work

### ISSUE THREAD

**Issue by donnybell** [OctopusDeploy/Issues#6800] opened 2021-03-19 19:04 UTC
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Helm external feeds with poorly formatted index.yaml (i.e. not semver compliant) don't work. However, despite this, they do work when using the helm client.

## What I expected to happen

Ideally, Octopus helm external feeds should have the same compatibility as the helm client.

## Steps to reproduce

1. Set up an external feed to a repo that lacks semver compliance (example: https://charts.jetstack.io/index.yaml)

## Affected versions

Tested on 2020.6.4671

**Octopus Server:**

## Workarounds

Call the helm executable directly or use a different repo

## Links

https://help.octopus.com/t/octopus-cannot-find-helm-packages-were-version-starts-with-v/26437

**Comment by dgard1981** [comment] 2021-06-01 08:32
Is there any news on this one at all?

I see that a similar fix was rolled out for the Docker Container Registry feeds in issue [6598](https://github.com/OctopusDeploy/Issues/issues/6598). This would save us from having to manually roll a scripted solution to pull a perfectly valid Helm chart from a registry.

**Comment by maelvls** [comment] 2021-06-01 09:27
Helm [does](https://helm.sh/docs/topics/charts/#the-chartyaml-file) require a SemVer-compliant version for its `version` field: 

> version: A SemVer 2 version (required)

which is also hinted in Helm's [conventions](https://helm.sh/docs/chart_best_practices/conventions/):

> Wherever possible, Helm uses [SemVer 2](https://semver.org/) to represent version numbers. Note that Docker image tags do not necessarily follow SemVer, and are thus considered an unfortunate exception to the rule.

The issue is that even though the spec says `version` should be a valid SemVer, Helm itself does not enforce it. One notable Helm chart still uses the non-SemVer `v1.2.3` is cert-manager (https://github.com/jetstack/cert-manager/issues/2380). I could not find any other example of such charts not respecting the SemVer convention.

Not sure how we can move this issue forward though 😞

**Comment by protonyx** [comment] 2022-06-16 23:43
I have another example from a kubernetes-sigs registry for the blob-csi-driver: https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts

There is only a single chart in that registry (blob-csi-driver), and most of the versions are prefixed with "v".

**Comment by garrettdass** [comment] 2022-06-17 16:34
Another report: [Internal Zendesk](https://octopus.zendesk.com/agent/tickets/91262)

**Comment by N-lson** [comment] 2022-07-06 03:20
- Similar exceptions for Docker/Maven are supported, this change would either involve having another `IVersion` like `DockerTag` but for Helm, or using `OctopusVersion` which handles `vX.Y.Z` format
- Also requires an update on the Calamari side
- Left some draft changes in [this branch](https://github.com/OctopusDeploy/OctopusDeploy/tree/nelson/helm-versions)

**Comment by esaporski** [comment] 2023-03-03 17:42
No updates on this issue? I'm trying to deploy `cert-manager` helm chart but I'm having a lot of trouble because of this. `cert-manager` should be using SemVer2 but Octopus Deploy should also allow deploying packages that don't comply to SemVer.

**Comment by razorsk8jz** [comment] 2023-07-11 20:15
This is holding us up as well - cert-manager is not able to be found in the external-feed for octopus - I am assuming due to the invalid semantic versioning

**Comment by dan-close** [comment] 2023-07-18 15:57
Client report: [Internal Zendesk](https://octopus.zendesk.com/agent/tickets/140213)

**Comment by hypdeb** [comment] 2023-09-09 15:06
Exactly the same issue here, unable to deploy cert-manager.

**Comment by scme0** [comment] 2024-02-19 23:19
This should be fixed now. It's a duplicate of #8478 which is fixed.

**Closed by scme0** 2024-02-19 23:19 UTC
Labels: kind/bug, feature/feeds
