### ISSUE TITLE
Pre-release tag in packages causing failed auto release creation - investigation

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#1512] opened 2015-03-12 03:57 UTC
Reports of automatic release creation not working - build logs showing pre-release package naming. Need this investigated as cause.

http://help.octopusdeploy.com/discussions/problems/31362

**Comment by alfhenrik** [comment] 2015-03-12 23:40
Due to the package being a pre-release version, when we query for the latest package it is not being picked up.

We're currently using this `packageRepositor.FindPackagesById(nugetPackageId).FirstOrDefault(p => p.IsLatestVersion);` to find the latest version of a package. `IPackage.IsLatestVersion` returns `false` if the package version has a `SpecialVersion` (i.e. `1.0.0.0-beta` where `-beta` is the `SpecialVersion`) and as such is not picked up when we query for it.

The fix for this would be to modify our query above to not look at `IPackage.IsLatestVersion` and instead sort the list of packages by version descending and then pick the first one from that list.

**Comment by Damovisa** [comment] 2015-03-24 04:44
When a package is pushed that will trigger a release, we use the pushed version. To determine whether the package is new, we compare the Semantic Version - which means pre-release versions will come before stable versions.

For example (assuming ARC is set up for a step using this package), `Package.1.0.0.1-dev.nupkg` will *not* trigger a release if there's already a `Package.1.0.0.1.nupkg` present. But it *will* trigger a release if the current version is `Package.1.0.0.0.nupkg`.

We *do* use the `IsLatestVersion` to get all the other packages in the project. This results in only the stable versions being used. So if `AnotherPackage` is unpacked in a different process step, `AnotherPackage.1.0.0.1-dev.nupkg` will never be used.

I've simplified/fixed the logic and added better logging as part of the fix for #1515, and I can't reproduce an error any more. I strongly suspect that fix will resolve this issue.

**Comment by Damovisa** [comment] 2015-03-25 04:51
For the package used to trigger a release, we use the version that was pushed and compare the Semantic Version. Pre-release versions will be higher than stable versions. We only look for the latest version of _other_ nuget packages required for the project, so this is unlikely to be the cause.

That said, I can no longer reproduce this issue, so I strongly suspect it has been fixed as a result of fixing #1515.

The next Octopus update should simplify the logic and provide better logging to help if the issue continues.

**Closed** 2015-04-01 05:04 UTC
Labels: 3 - Done, bug
