### ISSUE TITLE
DSC cTentacleAgent $TentacleHomeDirectory doesn't accept whitespace chars

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3226] opened 2017-02-27 04:27 UTC
> If you use 'c:\give me white\spaces please' the MSI install part till stall forever.
>
>Also in that context there seem to be no error handling of msi installs that fail to start because of bad parameters.

Source: https://github.com/OctopusDeploy/OctopusDSC/issues/43

**Comment by matt-richardson** [comment] 2017-07-12 05:35
Closing as duplicate of https://github.com/OctopusDeploy/OctopusDSC/issues/43

**Closed by matt-richardson** 2017-07-12 05:35 UTC
Labels: area/infrastructure
