### ISSUE TITLE
Can only select variables for step template account parameters

### ISSUE THREAD

**Issue by TomPeters** [OctopusDeploy/Issues#5123] opened 2018-11-26 03:24 UTC
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If I create a step based on a step template and one of the step template parameters are an Account (eg Azure Account), then I can only select Account variables for the value for this parameter.

## What I expected to happen

I would expect that I can also select Accounts (not just variables) since this is what I can do for steps that aren't based on step templates.

## Steps to reproduce

1. Create an Azure Account called "My Azure Subscription"
2. Firstly observe behavior in ordinary steps (not based on a step template): Create an Azure Powershell Script step and see that you can select "My Azure Subscription" for the account
![image](https://user-images.githubusercontent.com/1892715/48991286-0eb95380-f17e-11e8-8194-985b46dee222.png)
3. Create a step template based on the Azure Powershell Script step.
4. Add an Azure Account parameter to this step template, and bind it to the Account field on the step details.
![image](https://user-images.githubusercontent.com/1892715/48991308-2ee91280-f17e-11e8-81d5-64b33883d415.png)
![image](https://user-images.githubusercontent.com/1892715/48991316-37414d80-f17e-11e8-8ea7-1a6548fa6351.png)
5. Create a step in your deployment process based off this step template.
6. Try to select an account. You should be able to see the same accounts you could select in step 2, but you can't.
![image](https://user-images.githubusercontent.com/1892715/48991374-5fc94780-f17e-11e8-9006-91ab83b94ecb.png)

## Affected versions

Found in Octopus Server 2018.9.11

## Workarounds

Create a project variable linked to the account you want to select, then reference that variables from your step.

## Links

https://secure.helpscout.net/conversation/715163907

**Comment by thebigmoosey** [comment] 2018-11-26 03:32
Closing, duplicate of https://github.com/OctopusDeploy/Issues/issues/4117

**Closed by thebigmoosey** 2018-11-26 03:32 UTC
Labels: area/cloud, kind/bug
