### ISSUE TITLE
A rolling step with the first action server script step and second action manual intervention will always run regardless of role

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#2734] opened 2016-09-08 22:54 UTC
Define a process:

Server script step on role app-server
Manual intervention child step

Script step on role web-server

Release/deploy to a web-server and the app-server rolling step will run.

Behaves correctly if there is a Tentacle-side step inside the rolling step.

**Comment by markryd** [comment] 2017-01-12 05:13
This appears to have been fixed in the meantime. Unable to reproduce in Octopus 3.7.14:

```
Task ID:        ServerTasks-437265
Task status:    Success
Task queued:    Thursday, January 12, 2017 5:01 AM
Task started:   Thursday, January 12, 2017 5:01 AM
Task duration:  5 seconds
Server version: 3.7.15+Branch.master.Sha.2e6684ee1208cdb62c89d3edf7695834a5eb810a

                    | == Success: Deploy Mark's Test release 0.0.12 to Acceptance ==
05:01:55   Info     |   Deploying only to these specifically included machines: AWeb01
05:01:55   Verbose  |   Guided failure is not enabled for this task
05:02:00   Info     |   The deployment completed successfully.
                    | 
                    |   == Success: Step 1: Run a script on server for app-server ==
05:01:55   Info     |     Skipping this step as no machines were found in the role: app-server
05:01:55   Verbose  |     Run a script on server for app-server completed
                    |   
                    |   == Success: Step 2: Run a script on web-server ==
05:02:00   Verbose  |     Run a script on web-server completed
                    |   
                    |     Success: AWeb01
05:01:55   Verbose  |       Octopus Server version: 3.7.15+Branch.master.Sha.2e6684ee1208cdb62c89d3edf7695834a5eb810a
05:01:55   Verbose  |       Environment Information:
                    |       OperatingSystem: Microsoft Windows NT 6.2.9200.0
                    |       OsBitVersion: x64
                    |       Is64BitProcess: True
                    |       CurrentUser: NT AUTHORITY\SYSTEM
                    |       MachineName: DEMO
                    |       ProcessorCount: 4
                    |       CurrentDirectory: C:\Windows\system32
                    |       TempDirectory: C:\Windows\TEMP\
                    |       HostProcessName: Octopus.Server
05:01:55   Info     |       Executing script on 'AWeb01'
05:01:56   Verbose  |       Octopus Deploy: Calamari version 3.6.26+Branch.master.Sha.f622e5d591b3309b8aaf9f24dfd7baf69d6eb644
05:01:56   Verbose  |       Environment Information:
05:01:56   Verbose  |       OperatingSystem: Microsoft Windows NT 6.2.9200.0
05:01:56   Verbose  |       OsBitVersion: x64
05:01:56   Verbose  |       Is64BitProcess: True
05:01:56   Verbose  |       CurrentUser: NT AUTHORITY\SYSTEM
05:01:56   Verbose  |       MachineName: DEMO
05:01:56   Verbose  |       ProcessorCount: 4
05:01:56   Verbose  |       CurrentDirectory: C:\Octopus\AWeb01\Work\20170112050155-18
05:01:56   Verbose  |       TempDirectory: C:\Windows\TEMP\
05:01:56   Verbose  |       HostProcessName: Calamari
05:01:59   Verbose  |       Name                           Value
05:01:59   Verbose  |       ----                           -----
05:01:59   Verbose  |       PSVersion                      3.0
05:01:59   Verbose  |       WSManStackVersion              3.0
05:01:59   Verbose  |       SerializationVersion           1.1.0.1
05:01:59   Verbose  |       CLRVersion                     4.0.30319.18408
05:01:59   Verbose  |       BuildVersion                   6.2.9200.16628
05:01:59   Verbose  |       PSCompatibleVersions           {1.0, 2.0, 3.0}
05:01:59   Verbose  |       PSRemotingProtocolVersion      2.2
05:01:59   Verbose  |       PowerShell Environment Information:
05:01:59   Verbose  |       OperatingSystem: Microsoft Windows NT 6.2.9200.0
05:01:59   Verbose  |       OsBitVersion: x64
05:01:59   Verbose  |       Is64BitProcess: True
05:01:59   Verbose  |       CurrentUser: NT AUTHORITY\SYSTEM
05:01:59   Verbose  |       MachineName: DEMO
05:01:59   Verbose  |       ProcessorCount: 4
05:01:59   Verbose  |       CurrentDirectory: C:\Octopus\AWeb01\Work\20170112050155-18
05:01:59   Verbose  |       TempDirectory: C:\Windows\TEMP\
05:01:59   Verbose  |       HostProcessName: powershell
05:02:00   Verbose  |       TotalPhysicalMemory: 15728240 KB
05:02:00   Verbose  |       AvailablePhysicalMemory: 9567200 KB
05:02:00   Info     |       Hello from web-server
05:02:00   Verbose  |       Updating manifest with output variables
```

Reopen if we see this again.

**Closed by markryd** 2017-01-12 05:13 UTC
Labels: area/execution, bug
