### ISSUE TITLE
Support non-SemVer versions

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/Issues#5220] opened 2019-01-15 05:31 UTC
Historically Octopus has enforced the constraint that package versions must be [SemVer 2.0](https://semver.org/spec/v2.0.0.html).

This is often too restrictive when using Docker images, as container image tags are often not SemVer (browse [DockerHub](https://hub.docker.com) for examples).  

Some example tags from DockerHub are:
- `latest`
- `ubuntu-16.04-tfs-2018-u3-docker-18.06.1-ce-standard`
- `1`

Octopus only cares about package versions for ordering.  We should use a more tolerant parser, where we attempt to parse as SemVer, but fallback to simple string comparisons.

Reported by: https://help.octopus.com/t/specific-docker-repository-microsoft-vsts-agent-doesnt-work/22103

**Comment by MJRichardson** [comment] 2019-01-15 23:46
![](https://github.trello.services/images/mini-trello-icon.png) [Support "string" versions](https://trello.com/c/lcTNqM3h/177-support-string-versions)

**Comment by KennethBates** [comment] 2019-09-25 04:38
Also requested here: https://secure.helpscout.net/conversation/946708810/49626?folderId=954335 (private link)

**Comment by KennethBates** [comment] 2019-12-18 00:53
Another request: https://help.octopus.com/t/docker-images-not-found-when-creating-release/21848/7

**Comment by mac2000** [comment] 2020-05-21 05:51
Trying to figure out how to integrate existing google cloud kubernetes with google cloud container registry and move into octopus cloud, in my case I'm going to turn off automatic deployments and move into octopus, but there is already images and deployments, we used to add following tags to our images: `commit hash`, `branch name`, `latest`

So for production deployments we usually using `:master` label

For builds we are using Google Cloud Build which uses guids for build identifiers (e.g. there is no way to have `1.0.{build_number}` like in bitbucket pipelines, teamcity, ....) which makes this not trivial

Just wanted to share some more possible cases

**Comment by mcasperson** [comment] 2020-11-01 20:33
Duplicate of https://github.com/OctopusDeploy/Issues/issues/6598

**Closed by mcasperson** 2020-11-01 20:33 UTC
Labels: feature/containers, kind/enhancement, size/medium
