### ISSUE TITLE
Octopus.Server crashing

### ISSUE THREAD

**Issue by luk355** [OctopusDeploy/Issues#1441] opened 2015-01-21 10:15 UTC
About once a week at varios times the octopus.server crashes with an error bellow (taken from Event Viewer). No record about this event can be found in Octopus\Logs. Octopus is idle at that times. 

version: 2.5.3.245

![image](https://cloud.githubusercontent.com/assets/9592890/5834394/7f527bb4-a15d-11e4-9c53-5553ef43c55c.png)

Error:

Application: Octopus.Server.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Reflection.TargetInvocationException Stack: at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[]) at System.Delegate.DynamicInvokeImpl(System.Object[]) at Raven.Client.Linq.LinqPathProvider.GetValueFromExpressionWithoutConversion(System.Linq.Expressions.Expression, System.Object ByRef) at Raven.Client.Linq.LinqPathProvider.GetValueFromExpression(System.Linq.Expressions.Expression, System.Type) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitLessThanOrEqual(System.Linq.Expressions.BinaryExpression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitExpression(System.Linq.Expressions.Expression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitExpression(System.Linq.Expressions.Expression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitQueryableMethodCall(System.Linq.Expressions.MethodCallExpression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitMethodCall(System.Linq.Expressions.MethodCallExpression, Boolean) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitExpression(System.Linq.Expressions.Expression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitQueryableMethodCall(System.Linq.Expressions.MethodCallExpression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitMethodCall(System.Linq.Expressions.MethodCallExpression, Boolean) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitExpression(System.Linq.Expressions.Expression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitQueryableMethodCall(System.Linq.Expressions.MethodCallExpression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitMethodCall(System.Linq.Expressions.MethodCallExpression, Boolean) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitExpression(System.Linq.Expressions.Expression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetLuceneQueryFor(System.Linq.Expressions.Expression) at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Execute(System.Linq.Expressions.Expression) at Raven.Client.Linq.RavenQueryProvider`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].System.Linq.IQueryProvider.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.Expressions.Expression) at System.Linq.Queryable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.IQueryable`1<System.__Canon>, System.Linq.Expressions.Expression`1<System.Func`2<System.__Canon,Boolean>>) at Octopus.Server.Orchestration.TaskQueue.PollForMoreWorkOnBackgroundThread(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by vanessalove** [comment] 2015-01-27 23:48
Hi @luk355 - we have an issue for this : https://github.com/OctopusDeploy/Issues/issues/1099
It has some suggestions that do work for some customers, others are still seeing the crash. This issue will be resolved in 3.0 as it is caused by Raven and in 3.0 we are moving away from it. It does not have a set fix until then. 
Crash dumps and windows event logs are no real help at this time, as they all say the same thing.

**Closed by vanessalove** 2015-01-27 23:48 UTC
