### ISSUE TITLE
Cloning a runbook also clones its triggers

### ISSUE THREAD

**Issue by susanpann** [OctopusDeploy/Issues#7691] opened 2022-07-28 04:27 UTC
# Prerequisites
- [ ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [ ] I have discussed this in #feature-discussion or #backlog and the consensus is that this is something we plan on adding in the near future
- [ ] I have written a descriptive issue title
- [ ] I have linked the original source of this feature request
- [ ] I have labelled the value stream (area/core, area/steps, ...)
- [ ] I have added the kind/enhancement label

# The enhancement
Re-consider if a runbook's triggers should be cloned along with cloning a runbook. 

## What is the problem this solves or benefit it gives
Cloning the triggers along with the runbook can be unexpected - if a customer doesn't check it can result in unexpected runbook runs.

## Proposed solution
A solution could be to clone the triggers but have them disabled by default. 

## Links
Internal Ticket: https://octopus.zendesk.com/agent/tickets/93627
Internal Slack: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1658944815300799

**Comment by octokhor** [comment] 2022-08-15 02:23
Looks like this was intended? https://github.com/OctopusDeploy/OctopusDeploy/pull/4907

**Comment by octokhor** [comment] 2022-08-19 05:42
I'm closing this issue because this looks like what we intended and, unless we hear more about this being an issue for customers, it will remain closed. Thanks.

**Closed by octokhor** 2022-08-19 05:42 UTC
Labels: kind/enhancement, feature/runbooks, priority/low, state/triage, team/fire-and-motion, research/FnM PM
