### ISSUE TITLE
Cloning Child Manual Intervention step results in copying scoped TargetRole from Parent

### ISSUE THREAD

**Issue by RobMcCarther** [OctopusDeploy/Issues#8409] opened 2023-10-17 16:13 UTC
### Version

v2023.2 (build 13175) 

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Ran into this when they

- Export project from Production (this happened on two projects that have this manual intervention step).
- Import project to Development instance
- Promote to DBA Approval step (only runs for this stage in lifecycle) and get the following error message in DEV while we never got this in Production environment for same:

![image](https://github.com/OctopusDeploy/Issues/assets/139906297/ed6bed4b-3038-44cf-9754-584cdda214cb)

To get around it they had to set the **Deployment Targets Required** setting to “Allow deployments to be created when there are no deployment targets” when this was not necessary on the original project

We asked for their process JSON to take a look at things and noticed that the Manual Intervention Step had the following TargetRole which shouldn't be configurable through the usual Step UI: 
```
"Properties": { 
        "Octopus.Action.TargetRoles": "cea-dacpac" 
      },
```

Customer experienced this on v2023.2 (build 13175) in both environments.

### Reproduction

Repro Steps:
Add Manual intervention step as a Child step within a project, ensuring step group has a target role
Clone manual intervention step into a different project
Target role of parent step will be added to the manual intervention step in the new project

### Workaround

Support came up with the following script that should address removing TargetRoles from manual intervention steps. 
This should work and we're pretty sure we covered all edge-cases, but verify you are comfortable with the script and what it does before running. We also suggest backing up the Database

```
`# Set up project variables.
$octopusURL = "https://octopusurl/"
$APIKey = "API-XXXXXXXXXXXXXXX"
$header = @{ "X-Octopus-ApiKey" = $APIKey }
$spaceID = "Spaces-ID"
$dryRun = $true

# Grab all deployment processes.
$deploymentProcesses = Invoke-RestMethod -Method GET -uri "$($octopusUrl)/api/$($spaceID)/deploymentprocesses?&take=500" -headers $header

# Go through each deployment process.
foreach($deploymentProcess in $deploymentProcesses.items){

    # Check that process is not snapshot.
    if(!$deploymentProcess.Id.contains("-s-")){
        foreach($step in $deploymentProcess.Steps){

            # If step contains target role scoping and if step is manual intervention:
            if($step.Properties.'Octopus.Action.TargetRoles'){
                if($step.Actions.ActionType -eq "Octopus.Manual"){

                    # Extra check to be sure incorrect steps aren't modified.
                    if($step.Actions.ActionType -eq "Octopus.Script"){
                        break
                    }
                    
                    # Remove role scoping and PUT new process to project.
                    $step.Properties.PSObject.Properties.Remove('Octopus.Action.TargetRoles')
                    write-host "Script will modify step $($step.Name) in project $($deploymentProcess.ProjectId)"
                    
                    if(!$dryRun){
                    Invoke-RestMethod -method PUT -uri "$($octopusUrl)$($deploymentProcess.links.self)" -headers $header -body ($deploymentProcess | ConvertTo-JSON -depth 10)
                    }
                }
            }
        
        }
    }
}

if($dryRun){
    write-host "Dry run enabled - to perform modifications of projects change dryRun variable to false"
}`
```

**Comment by droyad** [comment] 2024-04-05 03:20
Duplicate of #8424

**Closed by droyad** 2024-04-05 03:20 UTC
Labels: kind/bug
