### ISSUE TITLE
Changing a process step parameter to be a bound variable, and then updating variables in a release and redeploying doesn't work

### ISSUE THREAD

**Issue by dazinator** [OctopusDeploy/Issues#1612] opened 2015-05-28 15:02 UTC
In the deployment process, I have one step, to deploy a nuget package, with the website feature enabled.

For the website feature's variables, for the website name, I typed a static value in i.e `MyWebsite`

I then:

1. Created a release
2. Deployed the release to Dev

I then

1. Went back into the process step, changed the statically typed value for website name to be a variable instead (which i then created under the variables tab)
2. Went into the existing release, and used the update variables button. This completed successfully.

I then

1. Deloyed the same release to Dev a second time.

Looking at the deployment logs it's still using the old static value for the website name variable..

Expectation:

If it can't update the variables in the release i'd expect it to warn me when clicking update variables.

**Comment by PaulStovell** [comment] 2015-07-17 07:02
The issue is that it was the deployment process that changed, not the variable set. We don't re-import deployment processes for a release because package steps might have been changed. I'm going to close this for now since at some point we'll re-evaluate if updating a deployment process should be allowed.

**Closed by PaulStovell** 2015-07-17 07:02 UTC

**Comment by dazinator** [comment] 2015-07-17 10:55
> The issue is that it was the deployment process that changed, not the variable set.

Then I don't think Octopus is meant to have allowed me to update the variables on a release when the deployment process has been changed?  Sounds like it doesn't think that changing a static parameter value on a process step, to be a variable binding expression, is a change of the deployment process.

**Comment by lukeskinner** [comment] 2015-07-20 17:46
The behavior of blocking a release from being updated was changed recently in https://github.com/OctopusDeploy/Issues/issues/1507 so you can update variables even if the process changes.
