### ISSUE TITLE
Reusing custom step template name does not allow new versions to be saved

### ISSUE THREAD

**Issue by brentkinney** [OctopusDeploy/Issues#7316] opened 2022-01-14 22:45 UTC
### Team

- [X] I've assigned a team label to this issue

### Version

2021.2.7727 & 2021.2.7852

### What happened?

When creating a Custom step template that shares the name of an older custom template that was renamed, you are unable to version (make changes) to that new template and receive the below error.

![image](https://user-images.githubusercontent.com/48770271/149594400-e0e1cb28-b22d-4d06-8fc7-7202c1b85a3c.png)

### Reproduction

Provided courtesy of a customer which I followed and verified:

"Reproduction steps:

1. Create a new script based Step template named “My Test Step Template”
2. Make a few changes to increment the version by a few increments (This in turn adds a record to the “ActionTemplateVersion” SQL DB table)
3. Here is the SQL cmd to look that up: SELECT Id, Name, Version, LatestActionTemplateId, ActionType FROM ActionTemplateVersion WHERE Name='My Test Step Template';
4. Now rename that step template to “My Test Step Template - Old”
5. Again save a few more iterations to it.
6. Now create and save a brand new step template named “My Test Step Template”
7. And try saving iterations to it. You will get the error I got above. 

The only workaround I am aware of for this is to delete the original step template now named “My Test Step Template - Old” to clear its history. You can then save iterations to the new step template after the original was deleted and the history was purged from the original. 

This also happens for imported steps as well if a previous step existed with that name and has a version history."

### Workaround

The only known workaround would be to use unique template names so the renaming problem wouldn't ever come up.  For example, you could name all custom templates with their name and date of creation to avoid the duplicate name problem in the future.  This would also help track when a particular template was first created and used.

- My Test Step Template (from 01-14-2022)

**Comment by tothegills** [comment] 2022-01-17 00:09
Duplicate of https://github.com/OctopusDeploy/Issues/issues/4001

**Closed by tothegills** 2022-01-17 00:09 UTC
Labels: kind/bug, feature/step-templates, state/triage, team/fire-and-motion
