### ISSUE TITLE
Tentacle Calamari status is not updated during Deployment Calamari Update process

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#2147] opened 2015-11-12 07:17 UTC
If a tentacle is flagged as needing a Calamari update is then deployed to, it gets the new calamari version as part of the deployment but its status still says that a deployment is needed.

![image](https://cloud.githubusercontent.com/assets/1830666/11112633/d0a485a2-8960-11e5-8cb6-a621b640194f.png)

![image](https://cloud.githubusercontent.com/assets/1830666/11112641/e2aee5da-8960-11e5-9fa0-4fa25c16fe77.png)

Presumably this would sort itself out on next health check so probably not a complete show stopper.

**Comment by michaelnoonan** [comment] 2015-11-13 05:15
Duplicate of https://github.com/OctopusDeploy/Issues/issues/2114

**Closed** 2015-11-13 05:15 UTC
Labels: duplicate
