### ISSUE TITLE
Lifecycle promotion does not work for particular lifecycle

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7395] opened 2022-02-24 00:23 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Annoying for us

### Version

2022.2.292

### Latest Version

I could reproduce the problem in the latest build

### What happened?

Two projects share a lifecycle configure to auto promote:

<img width="197" alt="image" src="https://user-images.githubusercontent.com/171197/155433167-12597dde-1883-45b4-b262-3685b8e691d3.png">

The promotions to External are not working for the [OctoNotes](https://deploy.octopus.app/app#/Spaces-842/projects/octonotes/deployments) and [OctoVersion](https://deploy.octopus.app/app#/Spaces-842/projects/octoversion/deployments) projects.

The deployment succeeded events are being process by the lifecycle promoter, but not deploying:

```
04:10:27   Verbose  |   Processing event block 4933858 to 4933864
04:10:27   Verbose  |   Processing automatic lifecycle promotions...
04:10:27   Verbose  |   Environments eligible for automatic release deployment: None
```

### Reproduction

See above.

### More Information

See internal report: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1645588500813629

### Workaround

Deploy manually (boo!)

**Comment by mlheureux** [comment] 2022-03-07 13:18
Also experiencing this issue here since we updated to latest version :(

**Comment by N-lson** [comment] 2022-03-23 00:37
Hey @mlheureux, could you check the lifecycle of the channel that the releases are part of and confirm that it's set to the expected lifecycle? We found that even though the project's default lifecycle was set to auto-deploy to both environments, the channel's lifecycle was set to a different one which only auto-deployed to the first environment. As per [our docs](https://octopus.com/docs/releases/channels#Channels-ControllingDeploymentLifecycle) if the lifecycle is set at the channel level it will override the project's default lifecycle.

If this isn't the case, I suggest reaching out to support@octopus.com and we'll be happy to help you further from there.

**Comment by N-lson** [comment] 2022-03-23 00:37
Closing as it seems to have been a misconfiguration on our instance.

**Closed by N-lson** 2022-03-23 00:37 UTC
Labels: kind/bug, state/triage, team/fire-and-motion

**Comment by mlheureux** [comment] 2022-03-23 13:07
Hi @N-lson , I double-checked and our Channel Lifecycle is correct and should be set to auto-deploy

So there might be another configuration elsewhere that is preventing this, but so far everything I checked is ok and still not auto-deploying, we're still noticing the issue

![image](https://user-images.githubusercontent.com/81432559/159706022-5aa11c37-bc7f-446a-8bf1-0655d2034260.png)

![image](https://user-images.githubusercontent.com/81432559/159706040-fe5a0de0-5a34-45fb-b24c-920bfa0941fd.png)

**Comment by N-lson** [comment] 2022-03-23 23:51
Thanks @mlheureux! It looks like those phases aren't being auto-deployed to as they're optional phases. I've raised a quick discussion internally and we've come to the conclusion that this is intentional behavior, but it's not being properly reflected in the UI or in our docs. I've raised an issue https://github.com/OctopusDeploy/Issues/issues/7446 to make it clearer that optional phases are ignored when evaluating any phases for auto-deployments.

**Comment by mlheureux** [comment] 2022-03-24 18:42
Well @N-lson  that is exactly our situation and your comments helped us resolve our issue

The fact that the phases were Optional was causing the issue, just making them mandatory got us back to the expected behavior we previously had, it's all auto-deploying again !

I agree with you that this behavior makes total sense, but the UI could be a little improved to help avoid the mistake

Thanks again for your ideas and support on that one!
