### ISSUE TITLE
Upgrading versions can cause the model to be invalid, with no way of fixing

### ISSUE THREAD

**Issue by distantcam** [OctopusDeploy/Issues#3914] opened 2017-11-13 01:57 UTC
Several upgrades over time have sometimes caused models to no longer be valid. For example step names didn't have to be unique, and then they did. So when a customer upgrades from one version to the next their projects are no longer deployable.

On top of that, the project can't be fixed because editing each step requires the whole project to pass validation before it will save. This means editing the whole project in one go, which we don't have in the UI.

**Comment by distantcam** [comment] 2017-11-13 01:59
One option could be to add a validation flag to the project, so that during upgrades projects can be marked as invalid. Then in the editor invalid projects can still be edited, but not used for deployments until they're fixed.

**Comment by pawelpabich** [comment] 2017-11-15 05:16
@distantcam if I understand correctly this happens when there was a change to a model but the data has not been migrated.  If so, we need to make sure we always migrate data. We've had cases like that before.

**Comment by distantcam** [comment] 2017-11-15 05:37
In the project step/action example I was told migration could not be done because it might break scripts that rely on the name of the step. That's what has lead to the support ticket for this.

https://help.octopusdeploy.com/discussions/problems/62647

**Comment by pawelpabich** [comment] 2017-11-15 06:02
In such a case we should have done what the customers says, break the upgrade. Also, I think this particual problem is already fixed in 4 where you can update the name of both actions and steps.

**Comment by distantcam** [comment] 2017-11-15 06:09
Nice!

So is there a way of preventing future migrations from breaking things going forward? Or maybe just more diligence with migrations? I'm more concerned with migrations in general than this specific example.

**Comment by pawelpabich** [comment] 2017-11-15 06:22
I think we should either migrate the data automatically (default) or detect data that can't be migrated and break the upgrade process with a clear message that describes what needs to be done.  Hopefully there will be ways around it like fixing the step rename process in this example.  If not, we will have to add it to our installation process.  

The worst solution is to skip migrations. We've had numerous cases where it took days to diagnose problems caused by data that was not migrated.

**Closed** 2017-11-22 04:13 UTC
Labels: area/modelling, bug
