### ISSUE TITLE
Machine preview on the advanced deployment view is incorrect even when selecting a single tenant

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/Issues#3178] opened 2017-02-15 22:11 UTC
# Problem

Source: https://secure.helpscout.net/conversation/319167840/13256/?folderId=557082

From my testing and code inspection this bug is a UI logic problem which only occurs when:
​
​1. You allocate the machines to tenants using tenant tags
​2. You select the tenants to be deployed by their name (instead of tag)

This code from `portal\app\areas\projects\controllers\project_deployment_create_controller.js` is too simplistic and doesn't leverage the server-side `TenantTester`:

```
machinesPromise.then(function (availableMachines) {
    $scope.machinesApplicableToThisDeployment = availableMachines.filter(function (machine) {
        if ($scope.view.deploymentType === 'tenant') {
            return ($scope.view.resultantTenants && $scope.view.resultantTenants.length > 0 && $scope.view.resultantTenants.filter(function (tenantId) {
                    return machine.TenantIds.indexOf(tenantId) >= 0;
                }).length > 0)
                || ($scope.view.selectedTenantTags && $scope.view.selectedTenantTags.length > 0 && $scope.view.selectedTenantTags.filter(function (tag) {
                    return machine.TenantTags.indexOf(tag) >= 0;
                }).length > 0) 
                || machine.TenantTags.length !== 0;
        }

        return (machine.TenantIds.length === 0 && machine.TenantTags.length === 0);
    });
```

# Reproduction

1. Create two machines and scope them to different tenants
2. Create a release
3. Go to the advanced screen for a deployment to a single tenant and the machine preview should only include the machines available for that tenant - perfect
4. Now create a tenant tag set and some tags
5. Now tag some tenants and allocate the machines using tenant tags (instead of specific tenants)
6. Go to the advanced screen for a deployment to a single tenant and the machine preview will show the wrong list of included machines

It looks like the logic in the UI which interprets tenant tag allocated machines is not working correctly. The server-side code does the correct filtering, and the deployment runs to the correct machines.

![image](https://cloud.githubusercontent.com/assets/1627582/22997762/7c30429c-f41f-11e6-97e7-94faedc5b04e.png)

# Workaround

1. You are safe to ignore the machine preview on the advanced deployment screen - it is inaccurate, but the server-side logic has several layers of checks to prevent deploying to the wrong machines.
2. You can work around the UI bug by allocating the machines directly to tenants (by name) instead of using tenant tags.

**Comment by michaelnoonan** [comment] 2017-02-15 23:05
![](https://github.trello.services/images/mini-trello-icon.png) [Machine preview on the advanced deployment view is incorrect even when selecting a single tenant](https://trello.com/c/12FTa746/132-machine-preview-on-the-advanced-deployment-view-is-incorrect-even-when-selecting-a-single-tenant)

**Comment by MJRichardson** [comment] 2017-03-06 02:23
Two more reports:

- https://secure.helpscout.net/conversation/328025967?folderId=557077
- http://help.octopusdeploy.com/discussions/questions/11019

**Comment by clottman** [comment] 2017-03-15 21:43
Since finding this bug, I've always deployed using "Include specific deployment targets" to include only the machines that I expect to be part of the tenant I'm targeting. Today, I forgot. The deployment started running on all of my production machines - not just the one for the tenant I chose at the top. 

On another attempt, I mismatched the tenant and the 'Include specific deployment targets'. In that field, I had the name of a machine that is in a different, similarly named tenant. The deploy used variables scoped to the machine in the 'include specific' field, and ran on that machine. (Not the machine that is in the selected tenant) I would expect that the environment/tenant selected at the top of the deploy screen takes priority, and that machines under 'include specific' would be valid only if they're actually part of the tenant I'm deploying to.

**Comment by DanielSundberg** [comment] 2017-04-12 16:55
Sorry for just doing +1 but this is a huge issue for my project. Any idea of when it will be fixed?

**Comment by michaelnoonan** [comment] 2017-06-13 07:43
We are trying to get to this bug soon, but it involves a fairly large chunk of work. We'll keep posted on this issue once we start working on it. :)

**Comment by michaelnoonan** [comment] 2017-06-13 07:46
Oooh, I should confirm, we have proven this is only a UI bug, even in the cases reported earlier in this thread. If you ignore the preview, we have several checks and balances in place during the deployment which work as expected, and only target the expected machines.

In all cases so far where unexpected machines were targeted, the machines were being allocated to more tenants than expected due to either:

- extra tags being added to the machine by accident
- extra tags being added to a tenant by accident

The best way to tell is by looking at the Preview/Design dialog on the Machine to confirm which tenants are allocated to the machine.

**Comment by vanessalove** [comment] 2017-07-21 00:00
Another report http://help.octopusdeploy.com/discussions/questions/12356

**Comment by distantcam** [comment] 2017-07-31 07:38
I have verified this has been fixed in 3.15.1.

**Closed** 2017-07-31 07:38 UTC
Labels: area/scale, bug, feature/tenants, priority

**Comment by ilyabreev** [comment] 2017-10-17 11:07
3.15.8
![2017-10-17_14-03-35](https://user-images.githubusercontent.com/1045399/31661616-09e063d6-b344-11e7-86bd-e6fd221e30e1.png)
"Advanced" link shows that target machine is striked out. 
But deployment on this machine succeeds anyway.
Deployment behaviour is correct but UI gives us incorrect info about deployment.

**Comment by MJRichardson** [comment] 2017-10-25 23:04
@ilyabreev we have completely re-designed this page as part of Octopus 4.0.
This is currently in alpha-testing, and should be widely released in the next few weeks.
Hopefully we will have a post dedicated to the new deployment page in [this blog series](https://octopus.com/blog/octopus-v4-blog-series-kickoff), if you're interested
.
We apologize for the misleading information in the current version.

**Comment by ilyabreev** [comment] 2017-10-26 04:03
@MJRichardson thank you for information. We’re can’t wait 4.0 to release.

**Comment by DanielSundberg** [comment] 2017-10-26 05:14
So it's great that the UI bug will be solved in 4.0, can't wait to get my hands on the new UI. 

However, I have experienced the same issue as @clottman talks about: 

````
Since finding this bug, I've always deployed using "Include specific deployment targets" to include only the machines that I expect to be part of the tenant I'm targeting. Today, I forgot. The deployment started running on all of my production machines - not just the one for the tenant I chose at the top.
````

Has this been addressed in another issue?

**Comment by clottman** [comment] 2017-10-26 15:51
@DanielSundberg Are you deploying using tenant tags? Check each of your machines for any tenant tags that shouldn't be there. We found that tenant tags belong on the tenant, not on the machine. Otherwise, when you deploy to a tenant tag, all machines (not just tenants) matching that tag will be deployed too.

**Comment by DanielSundberg** [comment] 2017-10-26 16:24
@clottman, that might have been the case for me actually. Ok, so not a bug after all. But this one is really, really difficult to understand..

**Comment by michaelnoonan** [comment] 2017-10-26 22:14
Hey all. We are working to make these parts easier to understand at a glance. Tenants bring a lot of flexibility, but they also carry a lot of complexity baggage with them. We want to make tenants as approachable as possible without giving up too much of the flexibility.

We really hope Octopus 4.x goes some of the way to making that happen and are busily redesigning certain parts of the application to suit. Depending on the time it takes these changes should be part of our public beta. I'd be very interested to hear your feedback!
