### ISSUE TITLE
Tentacle upgrade fails with `NullReferenceException`

### ISSUE THREAD

**Issue by zentron** [OctopusDeploy/Issues#3345] opened 2017-03-27 22:50 UTC
User reported following error when upgrading their tentacles.
![image](https://cloud.githubusercontent.com/assets/1830666/24343504/27bb7628-130a-11e7-9060-ffa4f88a8e9c.png)

Rerunning upgrade seemed to give same `NullReferenceException` but without the fatal autofac error
![image](https://cloud.githubusercontent.com/assets/1830666/24343521/4b36489e-130a-11e7-97f7-4c0c5bbe2033.png)

Tentacle was still updated sucessfully
![image](https://cloud.githubusercontent.com/assets/1830666/24343528/559c3d34-130a-11e7-9f0e-0329cdaa2e0c.png)

**Comment by droyad** [comment] 2017-03-29 06:54
Duplicate of #3355

**Closed by droyad** 2017-03-29 06:54 UTC
Labels: area/execution, bug
