### ISSUE TITLE
Using an AWS S3 Bucket Feed and setting the package download to download on target throws errors

### ISSUE THREAD

**Issue by AdamHollow49** [OctopusDeploy/Issues#8188] opened 2023-06-08 13:59 UTC
### Severity

S3 bucket feeds are unusable unless downloading directly to server

### Version

2022.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When attempting to use an S3 bucket feed in a transfer/deploy a package or as a reference package in a Run a Script step, if you set the package to download directly on the target you are met with errors in the deployment.

### Reproduction

1. Create an S3 Bucket Feed.
2. Create a new project.
3. Add a Deploy a Package step to the project.
4. Select the S3 Bucket Feed and configure the package to be downloaded directly to the target.
5. Save and create a new release and deploy the process.

### Error and Stacktrace

```shell
13:22:07   Fatal    |       The remote script failed with exit code 1
13:22:07   Verbose  |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.SuccessArbitrator.ThrowIfNotSuccessful(IActionHandlerResult result) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/SuccessArbitrator.cs:line 22
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.ActionDispatch.AdHocActionDispatcher.Dispatch(Machine machine, ActionHandlerInvocation actionHandler, ITaskLog taskLog, CancellationToken cancellationToken, VariableCollection variables) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/ActionDispatch/AdHocActionDispatcher.cs:line 80
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.PackageAcquisitionExecutionHandlers.Invoke(ActionHandlerInvocation invocation, ITaskLog taskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/PackageAcquisitionExecutionHandlers.cs:line 150
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.PackageAcquisitionExecutionHandlers.DownloadPackage(String packageId, IVersion version, IFeed feed, ITaskLog taskLog, CancellationToken cancellationToken, PackageCachePolicy packageCachePolicy) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/PackageAcquisitionExecutionHandlers.cs:line 125
                    |       at Octopus.Server.Orchestration.Targets.Common.PackageStagingMediator.DownloadPackageOnAgent(PackageIdentity packageIdentity, IDeploymentPackageDownloader deploymentPackageDownloader, PackageAcquisitionExecutionHandlers execs, ITaskLog taskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/Targets/Common/PackageStagingMediator.cs:line 76
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.AcquireMachinePackageTask.StagePackage(PackageAcquisitionExecutionHandlers packageAcquisitionHandlers, ITaskLog stepTaskLog, ITaskLog deploymentTargetTaskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs:line 251
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.AcquireMachinePackageTask.<>c__DisplayClass28_0.<<Acquire>b__0>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs:line 143
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Core.Threading.SingleResultProcess`1.Perform(Func`2 workerTask, Action logAction, CancellationToken cancellationToken) in ./source/Octopus.Core/Threading/SingleResultProcess.cs:line 45
                    |       at Octopus.Core.Threading.SingleWorkerDoesWorkCoordinator`1.DoWork(String key, Func`2 workerTask, Action logAction, CancellationToken cancellationToken) in ./source/Octopus.Core/Threading/SingleWorkerDoesWorkCoordinator.cs:line 43
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.AcquireMachinePackageTask.Acquire(AcquiredPackageMap acquiredPackageMap, ITaskLog stepTaskLog, ITaskLog deploymentTargetTaskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs:line 141
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.AcquireMachinePackageTask.Acquire(AcquiredPackageMap acquiredPackageMap, ITaskLog stepTaskLog, ITaskLog deploymentTargetTaskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs:line 165
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Steps.Acquire.AcquireMachinePackageTask.Acquire(AcquiredPackageMap acquiredPackageMap, ITaskLog stepTaskLog, ITaskLog deploymentTargetTaskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Steps/Acquire/AcquireMachinePackageTask.cs:line 210
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass4_3`3.<<Execute>b__5>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 73
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.ExecuteWithoutGuidance(Func`2 callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Guidance.cs:line 144
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.Guidance.Execute(Func`2 callback, String actionName, Boolean actionIsRequiredToRun, ITaskLog taskLog, Action callbackOnExclude, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/Guidance.cs:line 74
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass4_3`3.<<Execute>b__4>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 80
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.TransientErrorDetectionExecutor.Execute(Func`2 action, ExecutionPlan plan, ITaskLog taskLog, CancellationToken cancellationToken, DeploymentTarget deploymentTarget) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/TransientErrorDetectionExecutor.cs:line 50
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.TransientErrorDetectionExecutor.Execute(Func`2 action, ExecutionPlan plan, ITaskLog taskLog, CancellationToken cancellationToken, DeploymentTarget deploymentTarget) in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/TransientErrorDetectionExecutor.cs:line 50
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass4_2`3.<<Execute>b__3>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 84
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass6_0`3.<<Execute>b__0>d.MoveNext() in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 94
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 92
                    |       at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 92
                    |       at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T1,T2,T3](Func`5 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 97
                    |       at Octopus.Server.Orchestration.ServerTasks.Deploy.PlannedStepControllers.AcquirePackagesStepController.<>c__DisplayClass4_1`3.<<Execute>b__2>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/Deploy/PlannedStepControllers/AcquirePackagesStepController.cs:line 87
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Orchestration.ServerTasks.ParallelWorkOrderAsync`1.<>c__DisplayClass7_1.<<Execute>b__3>d.MoveNext() in ./source/Octopus.Server/Orchestration/ServerTasks/ParallelWorkOrderAsync.cs:line 61
                    |       --- End of stack trace from previous location ---
                    |       at Octopus.Server.Orchestration.ServerTasks.OctoThreadClosureAsync`1.Execute(CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/ServerTasks/OctoThreadClosureAsync.cs:line 61
                    |     
                    |       Failed: Download package s3BucketName/PackageName v1.0.5 directly from AWS S3 Feed



13:22:07   Error    |         Failed to download package s3bucket/RandomQuotesNexusNuget v1.0.5 from feed: ''
```

**Comment by aviuziel-aidoc** [comment] 2023-09-18 10:39
Do you have an update on this bug? It prevents us from using S3 as an external feed

**Comment by IsaacCalligeros95** [comment] 2023-09-27 05:56
Hey @aviuziel-aidoc I've just picked up the work for this ticket and have a fix. This is an issue in Calamari so we'll need to backport the change to supported LTS branches for you to get this one. Which LTS version of Octopus Server are you currently running?

**Comment by IsaacCalligeros95** [comment] 2023-09-27 23:54
@aviuziel-aidoc Thanks for that! I'll keep you updated about the rollout progress, but this fix should be in the 2023.3 and 2023.4 streams in ~1-2 weeks. Thanks for your patience on this one.

**Comment by IsaacCalligeros95** [comment] 2023-09-27 23:55
This is a duplicate of https://github.com/OctopusDeploy/Issues/issues/7974

**Comment by Clare-Octopus** [comment] 2023-11-07 12:47
Unfortunately this issue is still happening, running tests on Octopus 2023.3.13094 I can deploy fine when connecting to an S3 feed using '`Octopus Server will download the package, then securely upload it to the Tentacles`' but when I try and use '`The package will be downloaded directly from the feed on the execution target`' on the same feed and package I get:

![image](https://github.com/OctopusDeploy/Issues/assets/92790462/65bea065-a184-4184-958c-8591b0dde14c)

**Comment by Clare-Octopus** [comment] 2023-11-09 08:56
**Update to the above -** The engineers think they found the issue and it is to do with the package extension, we used to only check for the following extensions `".zip", ".tar.gz", ".tar.bz2", ".tar.gz", ".tgz", ".tar.bz"` but we have a recent change in to add support for more file types. 
 
Our engineers have put up a [PR](https://github.com/OctopusDeploy/Calamari/pull/1174) for Calamari to fix this, but will need to get some feedback and think on whether a part of the change is valid or not. 
 
This specific issue is related to https://github.com/OctopusDeploy/Issues/issues/7668 and less so this GitHub issue.
 
I just did a quick test on a .zip file in my S3 Bucket using `The package will be downloaded directly from the feed on the execution target` and it does deploy successfully. 

If you are using one of those file extensions I mentioned, and you are on a version higher than `2023.3.13091` you will be able to deploy, if you are on a version lower than `2023.3.13091` you will need to upgrade to that version or higher to be able to deploy the file extensions mentioned using `The package will be downloaded directly from the feed on the execution target`.
 

If you are using any other file types, hopefully we can get the PR accepted and merged and I will update this issue with what version that fix is in.

**Comment by IsaacCalligeros95** [comment] 2024-02-20 03:58
This has been resolved in 2023.3 on in https://github.com/OctopusDeploy/Calamari/pull/1174

**Closed by IsaacCalligeros95** 2024-02-20 03:58 UTC
Labels: kind/bug
