### ISSUE TITLE
NGINX config naming convention prevents multiple installs to one machine

### ISSUE THREAD

**Issue by Justin-Walsh** [OctopusDeploy/Issues#6215] opened 2020-03-02 15:54 UTC
# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug
The file naming convention for our NGINX step uses the package name for the configuration files, limiting the number of times a package can be deployed to a single server to 1. Assuming your package is called `file`, your config file will be `/etc/nginx/conf.d/file.conf`.

Because this is non-configurable, you can not deploy any other instances using that package to that machine, including to other environments, tenants, or package versions. Obviously, for a simple reverse proxy, this is fine, but for using NGINX as an actual webserver, it is very limiting.

## What I expected to happen

We should use a somewhat configurable filename here, such as the site name given in the step template, so they can use octostache variables etc. (See https://deploy.octopushq.com/app#/Spaces-342/projects/nginx/deployments/process - Internal Link)

## Steps to reproduce

1. Setup a linux target with NGINX installed and configured for multiple environments (Dev and Test) 
2. Setup NGINX Step template to deploy a package (see above link for example)
3. Deploy to Dev, examine config details on the server
4. Deploy to Prod, see that config details are the same file names.

## Affected versions

**Octopus Server: -> Latest** 

## Workarounds

No easy work arounds. 

## Links

**Comment by mcasperson** [comment] 2020-03-04 08:02
This bug is a duplicate of https://github.com/OctopusDeploy/Issues/issues/6216

**Closed by mcasperson** 2020-03-04 08:02 UTC
Labels: kind/bug
