### ISSUE TITLE
Adding version rule to channel heavily impacts performance

### ISSUE THREAD

**Issue by Dalmirog** [OctopusDeploy/Issues#2535] opened 2016-05-31 13:49 UTC
See ticket http://help.octopusdeploy.com/discussions/problems/46047 . Ping @MJRichardson as he has some thoughts about this.

Octopus version: `3.3.14`

**Comment by droyad** [comment] 2016-06-01 03:48
Duplicate of #2534

**Closed by droyad** 2016-06-01 03:48 UTC
