### ISSUE TITLE
Typing 'Releases' in Search and selecting 'Octopus Server Releases (builtin)' errors out

### ISSUE THREAD

**Issue by paraicoceallaigh** [OctopusDeploy/Issues#7051] opened 2021-09-16 00:36 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Non-blocking

### Version

2021.2.7428, also in 2021.2.7595 (hosted only)

### Latest Version

I could reproduce the problem in the latest version

### What happened?

Using Search in Cloud, searching for keyword 'Releases' and selecting 'Octopus Server Releases (builtin)' it tries to load the Feed call for that space and errors with a TypeError:
An unexpected error occurred in Octopus v2021.2.7428: "TypeError: Cannot read properties of undefined (reading 'text')"
in ExternalFeedInternal
in Unknown
in Unknown
in Page
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in Unknown
in RenderWithPage
in t
...

### Reproduction

Reproducible in any Hosted instance - just type Releases in Search.
https://samples.octopus.app/app#/Spaces-622/library/feeds/Feeds-1782

### Error and Stacktrace

```shell
An unexpected error occurred in Octopus v2021.2.7428: "TypeError: Cannot read properties of undefined (reading 'text')"
in ExternalFeedInternal
in Unknown
in Unknown
in Page
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in Unknown
in RenderWithPage
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in ExternalFeedRoutes
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in LibraryRoutes
in r
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in t
in RootRoutes
in withRouter(RootRoutes)
in SpaceLoader
in WithPersistedSpace
in p
in withRouter(Connect(WithPersistedSpace))
in div
in StandardLayoutInternal
in p
in t
in ErrorBoundaryInternal
in ReloadableRoute
in SecureRoute
in t
in Unknown
in Unknown
in t
in t
in Unknown
in DevToolsContextProvider
in ClientConnector
in I
in t
in Theme
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in ErrorBoundaryInternal
in c
in App
```

### More Information

Not present in previous or latest versions of Server. Cloud only. Visible in multiple browsers.

### Workaround

Don't type Releases in Search??

**Comment by TomPeters** [comment] 2021-09-16 01:08
I could reproduce this bug just by opening the linked URL at https://samples.octopus.app/app#/Spaces-622/library/feeds/Feeds-1782

![feed-error](https://user-images.githubusercontent.com/1892715/133532762-f0a30c54-b2fa-4091-96d6-e3660328f83a.png)

It looks like this is happening because this feed is a project feed.

![feedtype-error](https://user-images.githubusercontent.com/1892715/133532916-a8de31fb-c8b8-4609-91e8-9c0cc976cd65.png)

The feedTypeRegistry doesn't have an entry for project feed. I presume the External Feeds page is not supposed to work for the project feed, so perhaps this URL should be an invalid url that redirects to the 404 page? Or perhaps it should show something different for the project feed?

@paraicoceallaigh How did you get to this page? Was there a link somewhere in the app that took you here? If so, perhaps that link should not have existed, or perhaps it should have taken you elsewhere.

I'm going to assign this to fire and motion, because its specific to feeds and not part of the frontend platform.

**Comment by paraicoceallaigh** [comment] 2021-09-16 06:47
@TomPeters Followed the Repro instructions above. This is the link that is generated for the Search result for 'Releases' --> Octopus Server Releases (builtin). Tested in multiple Spaces.

**Comment by zentron** [comment] 2022-02-22 04:31
Looks liker this is just the "special" feed type used for deploy a package steps. It should be hidden entirely from the search

**Closed** 2022-08-04 07:50 UTC
Labels: kind/bug, area/hosted, size/tiny, state/triage, team/fire-and-motion, backloggrooming/discussed

**Comment by Octobob** [comment] 2022-08-04 10:52
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.7184 |

**Comment by Octobob** [comment] 2022-08-29 09:56
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.3 | 2022.3.7184 |
| 2022.4+ | _all releases_ |
