### ISSUE TITLE
Apparent handle leak exposed when querying NuGet feeds

### ISSUE THREAD

**Issue by nblumhardt** [OctopusDeploy/Issues#1071] opened 2014-07-15 23:55 UTC
```json
{
  "ErrorMessage": "The operation completed successfully",
  "FullException": "System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully\r\n   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)\r\n   at System.Windows.Threading.Dispatcher..ctor()\r\n   at MS.Internal.WeakEventTable..ctor()\r\n   at NuGet.SendingRequestEventManager.get_CurrentManager()\r\n   at NuGet.SendingRequestEventManager.AddListener(IHttpClientEvents source, IWeakEventListener listener)\r\n   at Octopus.Shared.Packages.OctopusPackageRepositoryFactory.CreateRepository(String packageSource) in y:\\work\\refs\\heads\\master\\source\\Octopus.Shared\\Packages\\OctopusPackageRepositoryFactory.cs:line 30\r\n   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Versions(String feedId, IEnumerable`1 packageIds) in y:\\work\\refs\\heads\\master\\source\\Octopus.Server\\Web\\Api\\Actions\\PackageSearchAction.cs:line 98\r\n   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Execute() in y:\\work\\refs\\heads\\master\\source\\Octopus.Server\\Web\\Api\\Actions\\PackageSearchAction.cs:line 41\r\n   at Octopus.Platform.Web.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in y:\\work\\refs\\heads\\master\\source\\Octopus.Platform.Web\\Api\\Responder.cs:line 162\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)\r\n   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )\r\n   at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass5.<.ctor>b__2(Object o) in y:\\work\\refs\\heads\\master\\source\\Octopus.Server\\Web\\Api\\OctopusRestApiModule.cs:line 47\r\n   at CallSite.Target(Closure , CallSite , Func`2 , Object )\r\n   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)"
}
```

```
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully\r
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)\r
   at System.Windows.Threading.Dispatcher..ctor()\r
   at MS.Internal.WeakEventTable..ctor()\r
   at NuGet.SendingRequestEventManager.get_CurrentManager()\r
   at NuGet.SendingRequestEventManager.AddListener(IHttpClientEvents source, IWeakEventListener listener)\r
   at Octopus.Shared.Packages.OctopusPackageRepositoryFactory.CreateRepository(String packageSource) in y:\\work\\refs\\heads\\master\\source\\Octopus.Shared\\Packages\\OctopusPackageRepositoryFactory.cs:line 30\r
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Versions(String feedId, IEnumerable`1 packageIds) in y:\\work\\refs\\heads\\master\\source\\Octopus.Server\\Web\\Api\\Actions\\PackageSearchAction.cs:line 98\r
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Execute() in y:\\work\\refs\\heads\\master\\source\\Octopus.Server\\Web\\Api\\Actions\\PackageSearchAction.cs:line 41\r
   at Octopus.Platform.Web.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in y:\\work\\refs\\heads\\master\\source\\Octopus.Platform.Web\\Api\\Responder.cs:line 162\r
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)\r
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )\r
   at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass5.<.ctor>b__2(Object o) in y:\\work\\refs\\heads\\master\\source\\Octopus.Server\\Web\\Api\\OctopusRestApiModule.cs:line 47\r
   at CallSite.Target(Closure , CallSite , Func`2 , Object )\r
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by vanessalove** [comment] 2015-02-13 03:33
Another report  https://octopusdeploy.uservoice.com/admin/tickets/3135

**Comment by vanessalove** [comment] 2015-03-02 00:01
Note from a customer RE this issue:

This happens to us several times a day on 2.5.12. I have since upgraded to 2.6.2 and they seems to have slowed the occurrences of this error and I have just upgraded to 2.6.3 last night. I would say given the reduction in occurrence kindly put this on hold and let me see if it occurs with any frequency rather than have Paul divert to this issue at this time. I will let you know how we do on this later next week and hopefully we can cancel it.

**Comment by DamianMac** [comment] 2015-03-04 03:37
Closing for now. We're seeing it less and think it should be less of an issue with our 3.0 use of nuget

**Comment by jmatthewsTW** [comment] 2015-04-08 10:10
I know this issue is closed, but we are also still seeing this problem on build 2.5.12.666. The only log we can find is below, and matches the stack traces others have posted before. It's also intermittent, and only affecting one of our projects. Restarting Octopus seems to have helped.

```
2015-04-08 10:45:26.7388  ERROR  Unhandled error on request: http://localhost:8082/api/feeds/feeds-1/packages?packageIds=SomePackage.SomeProduct by admin : The operation completed successfully
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Threading.Dispatcher..ctor()
   at MS.Internal.WeakEventTable..ctor()
   at NuGet.SendingRequestEventManager.get_CurrentManager()
   at NuGet.SendingRequestEventManager.AddListener(IHttpClientEvents source, IWeakEventListener listener)
   at Octopus.Shared.Packages.OctopusPackageRepositoryFactory.CreateRepository(String packageSource) in y:\work\refs\heads\master\source\Octopus.Shared\Packages\OctopusPackageRepositoryFactory.cs:line 30
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Versions(String feedId, IEnumerable`1 packageIds) in y:\work\refs\heads\master\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 98
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Execute() in y:\work\refs\heads\master\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 41
   at Octopus.Platform.Web.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in y:\work\refs\heads\master\source\Octopus.Platform.Web\Api\Responder.cs:line 163
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass5.<.ctor>b__2(Object o) in y:\work\refs\heads\master\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 47
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by gavin2n** [comment] 2015-04-08 10:18
Just happend to us again on 2.6.0.778 too.

Slight variation in the error log this time too. 

First time it errored about a lack of "storage", second time with the usual error. A restart of the service fixed both. 

At this point octopus deploy had consumed 95% of the servers memory. 

```
2015-04-07 12:56:36.2039  ERROR  Unhandled error on request: http://nuget.rgroup.co.uk:88/api/feeds/feeds-1/packages?packageIds=Amigo.Services.CollectionsState.SystemHost by TeamCity.RG@advantage.local : The operation completed successfully
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Threading.Dispatcher..ctor()
   at MS.Internal.WeakEventTable..ctor()
   at NuGet.SendingRequestEventManager.get_CurrentManager()
   at NuGet.SendingRequestEventManager.AddListener(IHttpClientEvents source, IWeakEventListener listener)
   at Octopus.Shared.Packages.OctopusPackageRepositoryFactory.CreateRepository(String packageSource) in y:\work\refs\heads\release\source\Octopus.Shared\Packages\OctopusPackageRepositoryFactory.cs:line 30
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Versions(String feedId, IEnumerable`1 packageIds) in y:\work\refs\heads\release\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 98
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Execute() in y:\work\refs\heads\release\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 41
   at Octopus.Platform.Web.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in y:\work\refs\heads\release\source\Octopus.Platform.Web\Api\Responder.cs:line 163
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass5.<.ctor>b__2(Object o) in y:\work\refs\heads\release\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 47
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
2015-04-07 13:43:03.3758  ERROR  Unhandled error on request: http://nuget.rgroup.co.uk:88/api/feeds/feeds-1/packages?packageIds=Amigo.Services.MessageFactory.ServiceHost by TeamCity.RG@advantage.local : Not enough storage is available to process this command
System.ComponentModel.Win32Exception (0x80004005): Not enough storage is available to process this command
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Threading.Dispatcher..ctor()
   at MS.Internal.WeakEventTable..ctor()
   at NuGet.SendingRequestEventManager.get_CurrentManager()
   at NuGet.SendingRequestEventManager.AddListener(IHttpClientEvents source, IWeakEventListener listener)
   at Octopus.Shared.Packages.OctopusPackageRepositoryFactory.CreateRepository(String packageSource) in y:\work\refs\heads\release\source\Octopus.Shared\Packages\OctopusPackageRepositoryFactory.cs:line 30
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Versions(String feedId, IEnumerable`1 packageIds) in y:\work\refs\heads\release\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 98
   at Octopus.Server.Web.Api.Actions.PackageSearchAction.Execute() in y:\work\refs\heads\release\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 41
   at Octopus.Platform.Web.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in y:\work\refs\heads\release\source\Octopus.Platform.Web\Api\Responder.cs:line 163
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , NancyContext )
   at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass5.<.ctor>b__2(Object o) in y:\work\refs\heads\release\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 47
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by vanessalove** [comment] 2015-05-15 03:26
Still getting reports of this. Worse part is it cant be predicted. I don't know how we can test this for 3.0 ?

**Comment by PaulStovell** [comment] 2015-05-20 06:59
We investigated this some more and are able to reproduce it (somewhat). 

NuGet uses a WeakEventManager (WPF) which uses a Dispatcher. In WPF applications, there's usually always one single Dispatcher for the whole application, which all threads post to. In console applications or Windows Services, Dispatcher.CurrentDispatcher always creates a new Dispatcher for each thread it's called from. Each new dispatcher allocates handles, which don't seem to be released. 

Since Octopus Server is a web application, each request is processed with a thread from the thread pool. Over time threads will come and go. It's possible that, over time, the number of dispatchers created would grow beyond the 10,000 or 32,000 handles allowed by Windows. Then, the error above occurs.

Of course Octopus uses handles for other things too - file I/O and so on - so the handle leaks could be occurring some other way. But this does seem to be possible to reproduce. 

**What you can do** when this error occurs, which would help greatly, is to use a tool like [Process Explorer](https://technet.microsoft.com/en-au/sysinternals/bb896653.aspx?f=255&MSPPError=-2147217396) to check the number of handles allocated to the process, and tell us about it. If it's more than a few thousand we'd really like to know.

**Comment by vanessalove** [comment] 2015-05-26 06:58
Re-opening as not resolved

**Comment by sammykun** [comment] 2015-05-28 18:30
Hi there, Octopus Team! Not sure if I should reply here, but we just started running into this issue today and was able to follow Paul's recommendation above regarding Process Explorer. I have a screenshot, and can provide more info. What is the best way to provide this info? Should I open up a ticket with support? Let me know how I can help, thanks!

**Comment by vanessalove** [comment] 2015-05-28 23:11
HI @sammykun - we have been able to replicate this and have submitted a bug request to NuGet. We do not require any further information. Restarting your Octopus Server service is the only known temporary fix.

**Comment by sammykun** [comment] 2015-05-28 23:19
Hi Vanessa, no problem. Glad it is being worked on. Restarting our service this morning did correct the issue.

**Comment by vanessalove** [comment] 2015-08-26 05:11
There are a few workarounds: restarting your server will temporarily fix it until the handle limit is reached. Or changing to reference a file share if you can for your NuGet feed.

Nuget 3.0 apparently fixes it, and we will create a new task to move to Nuget 3.0 when it is ready. But also leaving this task open for ease of search.

**Comment by michaelnoonan** [comment] 2015-11-13 08:22
I'm going to close this issue for now. The issue has a long history, including several attempts to work it out with the NuGet team. We are planning on moving to NuGet 3 in the near future which will fix this problem.

https://octopus.com/company/roadmap/why-was-this-closed

**Closed** 2015-11-13 08:24 UTC
Labels: bug, wontfix

**Comment by ccamburn** [comment] 2015-11-18 12:49
@michaelnoonan @vanessalove Is there a scheduled release number or a github issue we can track for when Octopus will move to NuGet 3.0? This is currently affecting our CI loop, occasionally requiring a restart, so I'd like to be able to upgrade when it's available.

**Comment by dknox20** [comment] 2015-12-01 14:32
This appears to still happen in Octopus 3 as it is happening after upgrading.  Any news on fixing this? 

Teamcity is hosting the Nuget feed
Teamcity is calling Octo.exe to create the release and it fails with 500

Randomly shows "Operation Completed Successfully"

**Comment by nirw** [comment] 2016-03-02 23:33
Hi Octopus Team,
I was hoping Octopus 3 will not have this issue which we somehow managed to workaround in V2.6 by an automatic weekly schedule restart of the service on the Octopus server.
Unfortunately about a week after the upgrade we encountered the issue again this time we were getting slightly new and confusing error message and not just the operation completed successfully - we also get "Not enough storage is available to process this command".
So I enabled the weekly scheduled task on the new (3.x) instance.
The problem is now that (even though we are restarting the service weekly which was our 2.6 workaround) we are seeing this more (and our volumes haven't grown so much since we upgraded).
I've re-scheduled the task to run twice a week, but it looks like 3.x made the problem worse for us.
Any thoughts?
Thanks,
Nir

**Comment by michaelnoonan** [comment] 2016-05-23 03:34
Just a note to say we've started work on upgrading to NuGet v3 (as part of supporting SemVer 2.0): https://github.com/OctopusDeploy/Issues/issues/2517

**Comment by ma499** [comment] 2016-05-23 16:28
We have encountered this problem with Octopus 3.2.23. A re-start of the Octopus Server re-solved the issue. As requested by @PaulStovell I looked at the handle count before re-starting. It was not too high, hovering between ~2,700 and ~3,000. After re-start it hovered between ~1,200 and ~1,500.

**Comment by adydub** [comment] 2016-06-07 10:53
We're also seeing this issue 3.3.12 using standalone NuGet repo server. Will try restart to workaround and will look forward seeing if the NuGet v3 work resolves. Let me know if any debug will be useful.

**Comment by gurufordy** [comment] 2016-08-04 10:41
I've just found this issue on 3.3.17 using Klondike NuGet server and my handles for Octopus Server is very low compared to the number @PaulStovell talks about.

![image](https://cloud.githubusercontent.com/assets/5593892/17399117/4ead1362-5a38-11e6-9768-fd2a5951a0df.png)

**Comment by scbond** [comment] 2016-09-12 23:51
Hi,

We have hit this issue over the past couple of days, Our handles for the Octopus server were also well below the ones mentioned by @PaulStovell and where sat around 3200.

I restarted the service and creating a release has resolved itself. We are using 3.3.23 and using Nexus as our Nuget server.

Thanks

**Comment by vanessalove** [comment] 2016-09-13 00:02
Hi All,

in 3.4 we upgraded the NuGet version that we use, and the NuGet team have let us know that this should resolve the issue.

Vanessa

**Comment by shyamhd** [comment] 2017-02-03 10:24
@vanessalove 
Hi am facing this issue some times.
Please check my logs 
```
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
[15:01:10][Octopus Deploy]    at MS.Win32.UnsafeNativeMethods.RegisterClassEx(WNDCLASSEX_D wc_d)
[15:01:10][Octopus Deploy]    at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
[15:01:10][Octopus Deploy]    at System.Windows.Threading.Dispatcher..ctor()
[15:01:10][Octopus Deploy]    at System.Windows.Threading.Dispatcher.get_CurrentDispatcher()
[15:01:10][Octopus Deploy]    at MS.Internal.WeakEventTable..ctor()
[15:01:10][Octopus Deploy]    at MS.Internal.WeakEventTable.get_CurrentWeakEventTable()
[15:01:10][Octopus Deploy]    at NuGet.SendingRequestEventManager.get_CurrentManager()
[15:01:10][Octopus Deploy]    at NuGet.DataServicePackageRepository..ctor(IHttpClient client, PackageDownloader packageDownloader)
[15:01:10][Octopus Deploy]    at Octopus.Core.Packages.OctopusPackageRepositoryFactory.CreateRepository(String packageSource) in Y:\work\refs\tags\3.2.22\source\Octopus.Core\Packages\OctopusPackageRepositoryFactory.cs:line 40
[15:01:10][Octopus Deploy]    at Octopus.Core.Packages.OctopusPackageRepositoryFactory.CreateRepository(String packageSource, ICredentials credentials) in Y:\work\refs\tags\3.2.22\source\Octopus.Core\Packages\OctopusPackageRepositoryFactory.cs:line 25
[15:01:10][Octopus Deploy]    at Octopus.Server.Web.Api.Actions.PackageSearchAction.Search(String feedId, String packageId, Boolean partialMatch, Boolean includeMultipleVersions, Boolean includeNotes, Boolean includePreRelease, Int32 take, IVersionSpec versionRange, Regex preReleaseTag) in Y:\work\refs\tags\3.2.22\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 67
[15:01:10][Octopus Deploy]    at Octopus.Server.Web.Api.Actions.PackageSearchAction.Execute() in Y:\work\refs\tags\3.2.22\source\Octopus.Server\Web\Api\Actions\PackageSearchAction.cs:line 55
[15:01:10][Octopus Deploy]    at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in Y:\work\refs\tags\3.2.22\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 162
[15:01:10][Octopus Deploy]    at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
[15:01:10][Octopus Deploy]    at Octopus.Server.Web.Api.OctopusRestApiModule.<>c__DisplayClass0_0.<.ctor>b__0(Object o) in Y:\work\refs\tags\3.2.22\source\Octopus.Server\Web\Api\OctopusRestApiModule.cs:line 46
[15:01:10][Octopus Deploy]    at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
[15:01:10][Octopus Deploy] -----------------------
````
Can you help me regarding this?
