### ISSUE TITLE
Long links in project description flow into page

### ISSUE THREAD

**Issue by DamianMac** [OctopusDeploy/Issues#1842] opened 2015-08-05 03:43 UTC
<img width="255" alt="unnamed" src="https://cloud.githubusercontent.com/assets/1187840/9077953/e6f61f0a-3b77-11e5-8c60-423cb129e480.png">

**Comment by vanessalove** [comment] 2015-08-05 04:53
relevant: http://community.octopusdeploy.com/t/ui-changes-relocate-the-description-field-resolved/420
decided not a bug

**Comment by michaelnoonan** [comment] 2015-08-23 23:14
Closing this Issue since the same point has been raised a few times and escalated to UserVoice:

https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/8970832-provide-another-location-to-display-detailed-proje

**Closed** 2015-08-23 23:15 UTC
Labels: enhancement
