### ISSUE TITLE
Manual Intervention in child steps prevents causes all subsequent deployments to the target to queue

### ISSUE THREAD

**Issue by OctopusBob** [OctopusDeploy/Issues#4928] opened 2018-09-28 15:34 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

For example, if I create a test project with just a normal manual intervention, I can queue multiple releases, and they all deploy independently. Everything works just fine. In this example the release 0.0.5 is in waiting in a manual intervention, but I still can create release 0.0.6 and deploy it.

![image](https://user-images.githubusercontent.com/38642825/46218250-c7dbe880-c309-11e8-8e5e-5abd28d55a80.png)

![image](https://user-images.githubusercontent.com/38642825/46218273-d0ccba00-c309-11e8-900d-a12f8b8c4f34.png)

![image](https://user-images.githubusercontent.com/38642825/46218285-d62a0480-c309-11e8-8158-03314901e897.png)

Now I am going to move the manual intervention as a child step in a deployment. This will cause future releases to be queued and not deployed until the previous releases manual interventions are answered.

![image](https://user-images.githubusercontent.com/38642825/46218298-db874f00-c309-11e8-93cf-0ab7060c138c.png)

![image](https://user-images.githubusercontent.com/38642825/46218313-e346f380-c309-11e8-964a-713a4bd9ca25.png)

![image](https://user-images.githubusercontent.com/38642825/46218325-e93cd480-c309-11e8-98be-581b85f241d9.png)

## What I expected to happen

The new second release would not be queued.

## Affected versions

2018.8.6

## Workarounds

Approve the first release causing the second release to queue up

## Links

Initial customer report: https://secure.helpscout.net/conversation/672493176/32801?folderId=2004019

**Comment by tothegills** [comment] 2018-11-14 03:51
There are two behaviours for manual intervention depending on the context of the step.  When a manual intervention is not in a child step the entire deployment gets paused and placed back into the task queue until the manual intervention is resolved.  This allows deployments of the same project/environment to proceed because the original deployment is no longer running.

When there is a manual intervention in a child step that intervention applies for each machine in the child step. When an intervention is encountered the deployment continues to run, waiting for each machine to be resolved. As each machine is resolved, the next in the rolling deployment starts. Because the deployment is executing all this time the rules for blocking other tasks to the same project/environment apply.  I think the best option in this scenario is to segregate the deployments, either by environment or tenant.

**Comment by tothegills** [comment] 2018-12-12 06:02
Closing because I believe it is working as intended.

**Closed by tothegills** 2018-12-12 06:02 UTC
Labels: action/investigate, area/execution, kind/bug
