### ISSUE TITLE
Overhaul of variable editing grid

### ISSUE THREAD

**Issue by vanessalove** [OctopusDeploy/Issues#2606] opened 2016-07-25 00:09 UTC
Currently the variable editing grid behaviour causes a lot of frustration and confusion for users. Things such as when you tab, enter, delete etc. It is a bit of a mess with consistency and you need a mouse to really move around when doing a large amount of editing in one sitting.

This should be more of a look at overhauling the grid itself than fix the small things that users complain about as that may make it worse ;)

(one example) Source: https://secure.helpscout.net/conversation/230387695/8639/?folderId=557080

**Comment by thebigmoosey** [comment] 2016-08-04 01:49
One specific case for the variables grid is the TAB key when entering new variables:

## Steps to reproduce
- Have multiple variables setup in your Project Variables screen
- Create a new variable name, then type the TAB character
- The focus is taken back to the first variable name, instead of the value for the new variable field that you would expect

Eg. I entered "MarkVar6" and hit TAB and the focus goes to my first variable in my list (very annoying when you have a long list of variables and are doing data entry)
<img width="1052" alt="screen shot 2016-08-04 at 11 32 34 am" src="https://cloud.githubusercontent.com/assets/819605/17387705/7ff57c88-5a39-11e6-82bd-35cf5ed06e4e.png">

**Comment by alfhenrik** [comment] 2016-09-08 02:34
Also, when you click the `Variable Name` field, sometimes it becomes unresponsive so you have to click out of it into the `Value` or `Scope` fields before being able to select the `Variable Name` field again and entering the name.

I have seen this locally, and also reported here: http://help.octopusdeploy.com/discussions/problems/47428

**Comment by mwoffenden** [comment] 2016-09-29 18:44
Variables editing _desperately needs a complete overhaul_, not just cosmetics.  The variable editor in OD the worst browser based editing I have ever used.  

How can I help move this along?

**Comment by ashmatthew** [comment] 2016-11-04 22:12
While I feel that "worst ever" is a bit harsh, I do disagree with the label - to me this is not an enhancement, but a bug that needs to be fixed sooner than later. 2.6.x behaved much better, and was very easy and intuitive to use.

**Comment by zentron** [comment] 2017-01-03 03:33
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Variables UI (773 Votes)](https://trello.com/c/bYldLYmK/11-improve-variables-ui-773-votes)

**Comment by vanessalove** [comment] 2017-01-05 12:09
When you have view permissions for variablesets but edit permissions for project variables you should be able to right click copy on the variableset values (variable name and value) to then paste it for when editing or creating project variables.

Henrik looked into this, but it is a limitation of the current grid editing library.

Source: http://help.octopusdeploy.com/discussions/problems/50261

**Comment by alfhenrik** [comment] 2017-01-24 23:27
Another scenario to take into account when redesigning the variable UI https://secure.helpscout.net/conversation/306794052/0/

**Comment by mwoffenden** [comment] 2017-01-25 14:38
**alfhenrik**, your link does not work:  

> The mailbox you requested is not available.
> You may not have permission to view this mailbox, or it no longer exists.

**Comment by matt-richardson** [comment] 2017-01-25 18:26
@mwoffenden - that is a link to a private support conversation.

**Comment by danielfischeroctopus** [comment] 2017-03-30 02:33
Another source with useful information: https://secure.helpscout.net/conversation/341709785/0/?folderId=845288

Clicking the value box is quite buggy, it only selects where you click for the first variable you edit. The cursor jumps to the end on subsequent variable editing after you type the first character.

**Comment by pawelpabich** [comment] 2017-05-15 02:07
Environments list in the scope object doesn't get updated properly 👍 
http://help.octopusdeploy.com/discussions/problems/51848-variable-with-no-scope
http://help.octopusdeploy.com/discussions/problems/54438

**Comment by KennethBates** [comment] 2017-05-17 04:16
Another aspect needing to be addressed in the overhaul.
When saving a change and click "Save" it doesn't save the change you've made. You must first click "Apply" and then "Save".

![save_variable_change](https://cloud.githubusercontent.com/assets/20388190/26138275/4e7c623a-3b0b-11e7-9310-5a0cc20c5b64.gif)

Source: https://secure.helpscout.net/conversation/365958170/15739/?folderId=954331 (private link)

**Comment by pawelpabich** [comment] 2017-05-24 05:54
User Voice: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/7192251-improve-variables-ui

**Comment by pawelpabich** [comment] 2017-05-24 22:37
Fix in v4

**Comment by PaulStovell** [comment] 2017-05-31 23:19
Some thoughts I had:

- Variables should be grouped by name - the group should become an object with a name, multiple scoped values, and a description
- Filtering should be more obvious - most people don't know it can be done
- Show warnings where a variable hasn't been defined for a given environment in the lifecycle, let them click to ignore it

**Comment by pawelpabich** [comment] 2017-06-16 04:04
We also might want to look at the way the variable data is persisted. In most cases only a subset of variables is sent to the client because the user doesn't have access to all variables. Because of that the server needs to do some work to figure our what has been changed. 

This has proven to cause quite a few issues so we might want to fix that as part of v4. Especially that we might need to break the API.

**Comment by pawelpabich** [comment] 2017-07-06 00:39
Just a quick update, we have started working on the variable editor and we have an [RFC](https://octopus.com/blog/variable-editor-update-rfc) that describes what what our plan is. Have a look and let us know what you think.

**Comment by droyad** [comment] 2017-10-09 05:27
Release Note: The variable editor has been overhauled

**Closed by droyad** 2017-10-09 05:27 UTC
Labels: area/modelling, enhancement

**Comment by NickJosevski** [comment] 2017-10-09 05:42
🎆

**Comment by mwoffenden** [comment] 2017-10-09 14:43
In which release will we see this?  And where can we get some advanced screen shots?

**Comment by pawelpabich** [comment] 2017-10-09 22:28
Hi @mwoffenden, you can play with the new editor in read only mode here https://v4.octopushq.com/. Also, we are about to start close Alpha release of Octopus. Would you like to participate in it ?

**Comment by mwoffenden** [comment] 2017-10-09 22:49
Yes, I would like to participate in the Alpha - thanks.

**Comment by pawelpabich** [comment] 2017-10-10 07:17
That would be great @mwoffenden. Can you please register [here]( https://docs.google.com/forms/d/e/1FAIpQLSeyjG0tXhtBjoANTlwZjNidsWsUhjGje41KSf1Tg2X0HbUqIg/viewform) ?
