### ISSUE TITLE
Tenant Variables are not Versioned

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Issues#6746] opened 2021-01-28 04:04 UTC
If a Tenant's variables are opened in two different tabs then edited and saved in turn, the last save overwrites the previous one. This is handled on project variables using a version field.

Other than deployment processes and variables, other resource types are not versioned like this.

💭 We could use the `DataVersion` field as our version specifier

*Affected Octopus Server Versions*: All that have tenant variables

**Comment by arthursoas** [comment] 2021-02-16 13:15
This is really annoying

**Comment by tuliorezende** [comment] 2021-02-16 13:22
> This is really annoying

A lot. We got a lot of problems due how the Tenant screen works.

**Comment by samwx** [comment] 2021-02-16 13:26
> > This is really annoying
> 
> A lot. We got a lot of problems due how the Tenant screen works.

Can't wait for!

**Comment by Estavaringo** [comment] 2021-04-14 13:41
Any perspective on solving this?

**Comment by droyad** [comment] 2021-04-15 00:18
My team has this in our backlog, but I can't give a timeline for it right now.

**Comment by andreminelli** [comment] 2021-10-15 10:58
@droyad , any news about this issue? An estimate at least?

**Comment by droyad** [comment] 2021-10-18 00:47
No sorry, right now things like #7020 and #6842 are sitting ahead of this.

**Comment by EricJangola** [comment] 2022-01-18 12:15
@droyad. any update about this problem? He is really annoying

**Comment by luizguicl** [comment] 2022-01-18 12:57
Updating Tenant variables is a task we do often in our projects. This issue is a big problem for us. As our company employees increase this problems get worse. Any update @droyad ?

**Comment by andrebires** [comment] 2022-01-18 13:55
Hi @droyad and Octopus folks, we have been using Octopus for almost 10 years now, since the time when @PaulStovell itself handled the issues, and we had a just single dev team. ​And it has been working great for all these years and has been a fundamental part to support our product development. 

Today, we have multiple teams using Octopus on daily basis for the release management of our product. 

The addition of the "Tenants" feature a couple of years ago came at a very appropriate moment when we were required to create multiple instances of our product for our growing number of customers. But it seems it was never intended to be used by more than one team and it would surprise me if it is used by big teams at all.

Just to illustrate the impact this issue has on our productivity, **we have an internal chat channel just for the devs to report that they are changing tenant variables**. Messages like “I will change the tenant variables of project X” and “I’m done” are sent multiple times a day. 

This is required because we had in the past **incidents on production due to inconsistent tenant variables**, which later we discovered that was caused by two people changing simultaneously the same tenant project.

Sorry for the “sentimental” introduction and as a SaaS company ourselves, we know that sometimes is hard to prioritize some customers' specific requirements. But after a year of being reported, and with the potential impact this problem may cause, it would be nice to have at least to have some mitigation, like there is in the project variables where there is a warning when values inconsistencies occur.

**Comment by droyad** [comment] 2022-01-18 23:03
Hi All,

The team that owns this Issue has just finished planning for this quarter. I'm please to say that is is now on our committed list and we will start designing out a solution to this in the next week or two.

I say designing as the feeling is that we could make this experience much better than just putting a version field on and walking away. We could redesign the UI or change the payload of what we load and save to make it narrower.

**Comment by andreminelli** [comment] 2022-01-19 11:35
Awesome, @droyad!
I look forward for more good news about it :)

**Comment by andrebires** [comment] 2022-01-19 12:16
> Hi All,
> 
> My team (who owns this Issue) has just finished planning for this quarter. I'm please to say that is is now on our committed list and we will start designing out a solution to this in the next week or two.
> 
> I say designing as the feeling is that we could make this experience much better than just putting a version field on and walking away. We could redesign the UI or change the payload of what we load and save to make it narrower.
> 
> We'll post further updates as we get stuck in on this.

Excellent news @droyad! Thanks for your reply.

**Comment by zentron** [comment] 2022-02-15 00:45
Updated progress on this item. 
Rather than rewriting the entire tenant variable system to make the changes more granular, the team will be introducing a token field that will be returned from the Tenant `/variables` endpoint which will be used to provide some optimistic concurrency checks on the set of all variables set in the scope of that tenant. 
If the token returned in the response does not match the token originally provided in the request to load that tenant's variables then the update will fail.
It will deliberately support providing _no_ token in the response to make the change backwards compatible.

This change might not improve every aspect of editing tenant variables but will provide a quick win to improve how users are currently working with them.

**Closed** 2022-02-24 23:20 UTC
Labels: kind/bug, feature/tenants, feature/variables, area/core, state/committed, team/fire-and-motion

**Comment by Octobob** [comment] 2022-02-25 02:23
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.385 |

**Comment by arthursoas** [comment] 2022-02-25 18:58
Do we need to set something up on Octopus to enable token on `/variables` , or that is the default behavior?

**Comment by susanpann** [comment] 2022-02-28 05:26
Hey @arthursoas, yes this is now the default behaviour - you won’t need to set up anything for it to work as it will automatically calculate and compare concurrency tokens when needed.

**Comment by Octobob** [comment] 2022-04-11 05:34
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.385 |

**Comment by Octobob** [comment] 2022-05-20 06:10
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |

**Comment by Octobob** [comment] 2022-05-24 00:19
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.1829 |
| 2022.3+ | _all releases_ |
