### ISSUE TITLE
Runbook environment selection does not include project default lifecycle

### ISSUE THREAD

**Issue by tothegills** [OctopusDeploy/Issues#7317] opened 2022-01-17 01:39 UTC
### Team

- [X] I've assigned a team label to this issue

### Severity

Annoying for some customers

### Version

2021.2.5105

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When a runbook is configured to use "Environments from Project Lifecycles" and there are two channels, one which inherits the project lifecycle and one with an explicit lifecycle, only the environments from the explicit-lifecycle-channel may be selected.

### Reproduction

Create two lifecycles:
- Default: Dev, Test, Prod
- Dev: Dev

Create a project with the Default lifecycle
Create a channel for the Dev lifecycle

Create a runbook and select "Environments from Project Lifecycles"
Create a run of the runbook and observer that only the Dev environment may be selected

See https://main.testoctopus.app/app#/Spaces-604/projects/runbook-environments/operations/runbooks/Runbooks-1081/runNow

### More Information

Request thread: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1642189452164100
I think it was introduced in https://github.com/OctopusDeploy/OctopusDeploy/commit/a8aa7740bdd3db97799cd0a5b694f866b85d2cde#diff-6ce38ea79446d99ba43a033395fcfb69a4083bab833d898d15c3ab5dca9ef656R95

**Comment by acodrington** [comment] 2022-01-19 04:10
Interestingly, this seems to be by design, as we have a unit test to explicitly verify this behaviour. 

It was introduced as part of [this fix](https://github.com/OctopusDeploy/OctopusDeploy/pull/6153) to address [this issue](https://github.com/OctopusDeploy/Issues/issues/6426).

I'm not familiar with the runbook requirements or the rationale for this particular feature, but maybe @andrewabest can shed some light as he was involved in tickets linked above.

**Comment by acodrington** [comment] 2022-01-21 08:23
The existing behaviour makes sense, but the regression appears in a corner case that was not covered by the unit tests.

A unit test to address this corner case has been added, and the bug has been fixed in https://github.com/OctopusDeploy/OctopusDeploy/pull/11204

**Closed by acodrington** 2022-01-21 08:23 UTC
Labels: kind/bug, tag/regression, team/config-as-code

**Comment by Octobob** [comment] 2022-01-23 21:46
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | _tbc_ |
| 2022.1 | _tbc_ |

**Comment by Octobob** [comment] 2022-01-24 07:14
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | _tbc_ |
| 2022.1 | 2022.1.456 |

**Comment by Octobob** [comment] 2022-01-25 00:57
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | 2021.3.12055 |
| 2022.1 | 2022.1.456 |

**Comment by Octobob** [comment] 2022-02-17 01:26
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | 2021.3.12055 |
| 2022.1 | 2022.1.456 |
| 2022.2+ | _all releases_ |

**Comment by Octobob** [comment] 2022-04-07 02:43
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2022.2 | 2022.2.0 |

**Comment by Octobob** [comment] 2022-04-11 05:37
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.2 | 2021.2.8043 |
| 2021.3 | 2021.3.12055 |
| 2022.1 | 2022.1.456 |
| 2022.2+ | _all releases_ |
