### ISSUE TITLE
Look at how we handle the limit for the amount of retry attempts on failing to apply retention policies.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeploy/Issues#5662] opened 2019-07-03 00:43 UTC
# Prerequisites

- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already requested
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this feature request
- [x] I have tagged the issue appropriately (area/*, kind/enhancement)

# The enhancement

We should apply some kind of limit to the amount of retry attempts we perform for applying retention policies during a deployment.

## What is the problem this solves or benefit it gives

As an example, while applying retention policies during a deployment, if you hit an `Access Denied` message, we retry many times for each file. This can take a very long time.

## Links

Internal Source: https://secure.helpscout.net/conversation/894065229/46751?folderId=845288

**Comment by droyad** [comment] 2019-07-10 22:59
Duplicate of #4781. Customer reported this in `2019.5.7`, it was fixed in `2019.5.8`

**Closed** 2019-07-10 22:59 UTC
Labels: kind/enhancement
