### ISSUE TITLE
'System.IndexOutOfRangeException: Release_ChannelId' error during retention policy

### ISSUE THREAD

**Issue by alfhenrik** [OctopusDeploy/Issues#2115] opened 2015-11-04 23:24 UTC
In 3.2, after upgrading from 3.1.5, the built-in package retention policy fails with the error in the Title.

Source: https://secure.helpscout.net/conversation/136195897/2842/

**Comment by mjrichardson** [comment] 2015-11-12 11:39
Duplicate of https://github.com/OctopusDeploy/Issues/issues/2142

**Closed by mjrichardson** 2015-11-12 11:39 UTC
Labels: duplicate
