### ISSUE TITLE
Channel version rule designer doesn't apply correct colour to  some versions

### ISSUE THREAD

**Issue by pawelpabich** [OctopusDeploy/Issues#2857] opened 2016-10-27 02:23 UTC
This is related to http://help.octopusdeploy.com/discussions/problems/48432.
All versions that are half red and half green should be displayed entirely in red because they are outside of the specified range.

![image](https://cloud.githubusercontent.com/assets/347637/19752366/06f473a4-9c40-11e6-9ab7-6534f317f5fc.png)

**Comment by matt-richardson** [comment] 2016-12-16 03:19
So, it turns out that this is by design. When a version+tag is half red, it is showing what part of it does not match the version/tag specification.
There is also a state where it can be dark orange, which indicates that its not a valid version number.

As this was presumed to be a bug by multiple people, we think we could improve the UX here so that its much more obvious.

**Comment by matt-richardson** [comment] 2016-12-16 03:21
Assigning to @jess-ross for some UX consideration.

**Comment by jess-ross** [comment] 2017-01-03 03:05
![](https://github.trello.services/images/mini-trello-icon.png) [Channel version rule designer doesn't apply correct colour to some versions](https://trello.com/c/sx4vibeF/41-channel-version-rule-designer-doesn-t-apply-correct-colour-to-some-versions)

**Comment by zentron** [comment] 2017-01-03 04:13
![](https://github.trello.services/images/mini-trello-icon.png) [Channel version rule designer doesn't apply correct colour to some versions](https://trello.com/c/JKHY29kc/34-channel-version-rule-designer-doesn-t-apply-correct-colour-to-some-versions)

**Comment by matt-richardson** [comment] 2017-02-13 00:47
Another related issue: https://secure.helpscout.net/conversation/316541534?folderId=557077

**Comment by JohnKeippel** [comment] 2017-07-24 19:12
I see that there is some expected, but maybe confusing, highlighting going on here in this issue, but I found what I believe to be an actual bug that may be in the same neighborhood. Viewing the same project:

In IE 11...
![2017-07-24_13-57-05](https://user-images.githubusercontent.com/396156/28539937-0fe19be6-7079-11e7-935b-c245db015a95.png)

In Chrome 59/Firefox 51...
![2017-07-24_13-55-11](https://user-images.githubusercontent.com/396156/28539938-0fe1f582-7079-11e7-99ca-0889f4ac08c0.png)

Given Microsoft's ways, and being stuck on Windows 7 at work, I can't be of much help testing <11 or Edge, but when loading the Design rule editor initially in IE 11, it will briefly flash the correct highlighting and then revert to what you see in the screen shot. Chrome and Firefox do not experience this issue.

**Comment by johnsimons** [comment] 2017-11-09 06:41
Release Note: We have added a gutter to the versions preview that explicitly shows what versions included or excluded from the rule
![image](https://user-images.githubusercontent.com/122651/32591827-c4ec96d8-c56c-11e7-909b-a96e32bc45c4.png)

**Closed by johnsimons** 2017-11-09 06:41 UTC
Labels: area/modelling, bug
