### ISSUE TITLE
Under load IIS deployments can hang

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#6740] opened 2021-01-21 23:17 UTC
# The bug

A race condition issue may exist with the IIS `ServerManager.CommitChanges` method. When executing this method on systems under high-load, the `CommitChanges` method returns too fast. (Note: below we confirm that it is the Octopus server under load, not the remote server)

While this bug has existed for some time, it seems the best way to cope with this when writing code is `Thead.Sleep` as pointed out in [this stackoverflow post](https://stackoverflow.com/questions/7446632/servermanager-commitchanges-makes-changes-with-a-slight-delay/7588790#7588790).

When used within Octopus and Calamari (for example [IISWebSite_BeforePostDeploy.ps1](https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Scripts/Octopus.Features.IISWebSite_BeforePostDeploy.ps1#L273) the issue becomes unavoidable (even with a `-Timeout` argument in the script) because `CommitChanges` exits before the `Set-ItemProperty` method has called `Wait` on it. The result is deployments get stuck while the script is waiting a void return from `CommitChanges` that has already occurred.

The investigation below comes from an initial PR by @miguelelvir when we first started working on this issue  
**Calamari dump showing wait in `SilentProcessRunner`**  
![image](https://user-images.githubusercontent.com/2205214/105400142-d3fbba80-5c24-11eb-9804-7f1233ce49b7.png)

**Dump from Powershell showing it's waiting on `Set-ItemProperty`**  
![image](https://user-images.githubusercontent.com/2205214/105400211-ec6bd500-5c24-11eb-8637-0c99b13a7bb9.png)

**ProcExp confirming that we're still stuck in the script (appcmd)**
![image](https://user-images.githubusercontent.com/2953962/72289627-8617a400-3619-11ea-994d-e6235e8ee4f9.PNG)

## What I expected to happen

IIS deployments do not hang even when Octopus server is under load.

## Affected versions

**Octopus Server:** v2020.5.5

## Workarounds

The customer has modified Calamari to timeout the execution of the script after a certain time.

## Links

https://github.com/OctopusDeploy/Calamari/pull/688
https://github.com/OctopusDeploy/Calamari/pull/468

Internal slack discussion about Set-ItemProperties freezing powershell.
https://octopusdeploy.slack.com/archives/C01GYCD6VUH/p1611720068088400

**Comment by johnsimons** [comment] 2021-01-21 23:20
Hi @leonio,

Can you tell me when you first encounter this issue, what version of Octopus?
How often does it happen? Is it every deployment?
When you say "under load", are you referring to the whole IIS instance, or just the single website?

Regards
John

**Comment by johnsimons** [comment] 2021-01-21 23:23
@leonio,

A few more questions.
Does this occur when creating a brand new website or updating an existing, or both?

**Comment by leonio** [comment] 2021-01-22 16:01
@johnsimons - Thanks so much for your help and continued assistance on this. Answers inline below.

> Can you tell me when you first encounter this issue, what version of Octopus?

We encountered this in 2019 (we can't remember the exact month) but our original PR for a timeout was sent in over a year ago, and if memory serves this was v3.x, the Calamari version was tagged 8.1.4.

> How often does it happen? Is it every deployment?

2% of the time (2/100 deployments) - however we're deploying 1000's each day so it's common enough to cause daily issues. When a deployment gets stuck we have no alerting mechanism, and typically find out only when manually inspecting deployments and notice a deployment has been stuck for three days 😱 

Typically the problem compounds on itself as by the time we notice, there are a number of deployments queued behind. As a result we need to manually cancel these queued deployments, otherwise we have difficulties avoiding service outages.

> When you say "under load", are you referring to the whole IIS instance, or just the single website?

Sorry for the misunderstanding here, it's the actual Octopus instance being under load that seems to correlate with this. However, we don't feel this is contributing to the bug, but it is more so related to the issue in `ServerManager` on the remote server. We can sometimes replicate this using just a single project deployment, but since it's a race condition on the deployment target, it's very difficult to reproduce reliably.

> Does this occur when creating a brand new website or updating an existing, or both?

We've always been updating sites, so we haven't observed this on a new site. However, our suspicion is that it could also occur for new sites.

> What version of IIS are you deploying into?

This has been an issue since v7 and has continued on throughout v10 (current)

**Comment by danielfischeroctopus** [comment] 2021-01-28 01:01
After some testing, we managed to identify an issue with the `Set-ItemProperties` cmdlet. When looping this command with some basic parameters on a machine at 100% CPU, PowerShell stopped responding. (Had to force end the task from task manager.)

Link to an internal slack discussion with my findings. https://octopusdeploy.slack.com/archives/C01GYCD6VUH/p1611720068088400

**Comment by andrewabest** [comment] 2021-04-19 00:12
This issue has been reported to be resolved internally. If you are experiencing this issue, we recommend updating Octopus to the latest `2020.1` release, as it should resolve the issue. 

Internal link: https://help.octopus.com/t/unable-to-use-calamari-azurescripting-with-custom-tentacle-package-directory/26166/45

**Closed by andrewabest** 2021-04-19 00:12 UTC
Labels: action/investigate, area/steps, kind/bug
