### ISSUE TITLE
Migrator export and DeploymentRelatedMachine

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6497] opened 2020-07-27 06:50 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Attempting to run an export either via the octopus manager or octopus.migrator.exe will result in an error if there are entries in the DeploymentRelatedMachine table.

## What I expected to happen

The export should complete successfully

## Steps to reproduce

1. Open Octopus Manager
2. Click Export Data
3. Follow steps through and initiate

### Log exerpt

```
Error: The class ‘DeploymentRelatedMachine’ has a document map with JSON storage set to TextOnly, but the query does not include the ‘JSON’ column. Queries against this type must include the JSON in the select clause. If you just want a few columns, use Nevermores’ ‘plain class’ or tuple support.
Error: System.InvalidOperationException
Error: at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderExpressionBuilder.AssertValidColumnOrdering()
Error: at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderExpressionBuilder.Build()
Error: at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.Compile(DocumentMap map, IDataReader firstRow)
Error: at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.<>c__DisplayClass5_0.b__0(String _)
Error: at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
Error: at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.GetCachedCompiledExpression(IDataReader dbDataReader, DocumentMap mapping)
Error: at Nevermore.Advanced.ReaderStrategies.Documents.DocumentReaderStrategy.<>c__DisplayClass4_11.<CreateReader>b__1(DbDataReader dbDataReader) Error: at Nevermore.Advanced.ReadTransaction.ProcessReader[TRecord](DbDataReader reader, PreparedCommand command)+MoveNext() Error: at Nevermore.Advanced.ReadTransaction.Stream[TRecord](PreparedCommand command)+MoveNext() Error: at Octopus.Migrator.Core.ExportProcess.ExportController.WriteDocuments(String singularNoun, IEnumerable1 documents, ExportFileNameOption fileNameOption)+MoveNext() in ExportController.cs:line 797
Error: at Octopus.Migrator.Core.ExportProcess.ExportController.Write(String singularNoun, IEnumerable1 documents, ExportFileNameOption fileNameOption) in ExportController.cs:line 576 Error: at Octopus.Migrator.Core.ExportProcess.ExportController.Export() in ExportController.cs:line 103 Error: at Octopus.Migrator.Cli.Commands.ExportCommand.Start() in ExportCommand.cs:line 89 Error: at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) Error: at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime) Error: at Octopus.Shared.Startup.ConsoleHost.Run(Action1 start, Action shutdown)
Error: at Octopus.Shared.Startup.OctopusProgram.RunHost(ICommandHost host)
Error: at Octopus.Shared.Startup.OctopusProgram.Run()
Error: -------------------------------------------------------------------------------
Error: Terminating process with exit code 100
Error: Full error details are available in the log files at:
Error: C:\Octopus\Logs
Error: C:\Users\paulc\AppData\Local\Octopus\Logs
Error: If you need help, please send these log files to https://octopus.com/support
Error: -------------------------------------------------------------------------------
Error:
Error: The previous command returned a non-zero exit code of: 100
Error: The command that failed was: “C:\Program Files\Octopus Deploy\Octopus\Octopus.Migrator.exe” export --instance “OctopusServer” --directory “C:\Backup” --password “XXX”
```

## Affected versions

**Octopus Server:** 2020.3.1

## Workarounds

None currently known

## Links
https://help.octopus.com/t/error-during-octopus-migrator-exe-export/25570
https://help.octopus.com/t/issue-with-export-after-upgrade-to-v2020-3-1/25459
[Internal Link](https://secure.helpscout.net/conversation/1259939987/69330?folderId=557077)
[Internal Link](https://secure.helpscout.net/conversation/1251434134/68912/)

**Comment by cygnetlego** [comment] 2020-08-03 03:34
Hi.  Any update on this issue?  If there is no ETA soon, we will need to consider a rollback where about two weeks of work will be lost.

**Comment by sourabhtewari** [comment] 2020-08-06 06:38
Hi Guys...any ETA on the bugfix?

**Comment by adrianhowchin** [comment] 2020-08-24 03:45
We have flagged this as an issue with product, but at this point we do not have capacity to assign an engineer to resolve the issue. We'll keep the issue open, but unfortunately we can not provide any guidance as to when it will be resolved.

**Comment by souladm** [comment] 2020-09-01 05:12
Hi. Did you tried 2020.3.4? Was it fixed there?

**Comment by Garfield2013** [comment] 2020-09-01 09:21
No I have not tried that - But yes hopefully 😅🤷🏻‍♂️

tir. 1. sep. 2020 kl. 09.12 skrev kosar <notifications@github.com>:

**Comment by cygnetlego** [comment] 2020-09-01 09:28
Sorry – no time to risk the upgrade.  Instead we have downgraded back to the Feb release where there are no issues for the moment considering the last update indicated no planned effort to address the issue that is easy to reproduce.

**Comment by Garfield2013** [comment] 2020-09-01 11:03
Can I just install the previous verison on top of the existing verison in
which backup doesn’t work? Did that work out well for you?

tir. 1. sep. 2020 kl. 13.28 skrev Sean Liew <notifications@github.com>:

**Comment by calverp** [comment] 2020-09-01 11:07
Installing a previous version is unlikely to work as it will detect that
the database is for a different version. Rolling back will require your
database to also be restored to a state prior to the upgrade.

**Comment by sourabhtewari** [comment] 2020-09-01 22:34
Nope. We had to rollback to an earlier database from the backup. Lost a few weeks worth of data in the process.

**Comment by andrewabest** [comment] 2020-09-04 04:41
We have developed a fix for this issue, which will be available in the upcoming `2020.5.0` release of Octopus. This should be available for download on Octopus.com in roughly 2 months time.

**Comment by andrewabest** [comment] 2020-09-04 04:42
Release note: Fixes issue with migrator failing to export when related machines exist in deployments

**Closed** 2020-09-04 04:45 UTC
Labels: kind/bug

**Comment by andrewabest** [comment] 2020-09-17 01:27
Hi all 👋

With the amount of ongoing customer interest regarding this particular fix, we have decided to back-port it to the `2020.4.0` release of Octopus, which will be available for download on Octopus.com in around 2 weeks.

**Comment by souladm** [comment] 2020-09-21 07:19
Looks like export works in 2020.4.0
https://i.imgur.com/u72ZsOx.png

Thanks, Octopus Team.
