### ISSUE TITLE
OctoPack raises errors when publishing packages exist in Octopus

### ISSUE THREAD

**Issue by juanonsoftware** [OctopusDeploy/Issues#2099] opened 2015-10-28 04:59 UTC
I receive some errors when run this command to publish all packages after built

msbuild XYZ.sln /t:Build /p:Configuration=Release /p:RunOctoPack=true /p:OctoPackPublishPackageToHttp=http://<my-server>:180/nuget/packages /p:OctoPackPublishApiKey=API-7JIQWHJJYYEYG7VYPMI

The problem is, if any package from the solution exists in NuGet, it raises some errors as below and build failed. Is it possible to make it report warnings instead, because there is a new package (new version) from one project.

  Pushing PACKAGE_NAME 1.0.12.0 to 'http://XYZ:180/nuget
  /packages'...
  Failed to process request. 'Bad Request'.
EXEC : The remote server returned an error : (400) Bad Request.. [D:\Wip\ProjectFile.csproj]
D:\Wip\...\packages\OctoPack.3.
0.44\tools\OctoPack.targets(105,5): error MSB3073: The command ""D:\Wip\...\packages\OctoPack.3.0.44\tools\NuG
et.exe" push "D:\Wip\...\obj\octopacked\PACKAGENAME.1.0.12.0.n
upkg" API-7JIQWHJ -s http://ws2008-r2:180/nuget/packages " ex
ited with code 1. [D:\Wip\...\XYZ.csproj]

**Comment by michaelnoonan** [comment] 2015-11-16 00:41
Closing this as a duplicate of https://github.com/OctopusDeploy/Issues/issues/1978

https://octopus.com/company/roadmap/why-was-this-closed

**Closed** 2015-11-16 00:41 UTC
Labels: duplicate
