### ISSUE TITLE
Unable to save existing script steps with package sources

### ISSUE THREAD

**Issue by calverp** [OctopusDeploy/Issues#6824] opened 2021-04-12 15:48 UTC
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [X] I have verified the problem exists in the latest version
- [X] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [X] I have written a descriptive issue title
- [X] I have linked the original source of this report
- [X] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

After upgrading a "Run as Script" step that has a Script Source set to "Script file inside a package" will generate a "Package was selected as the script-source but a primary package was not selected" error whenever any save is attempted.

## What I expected to happen

Changes should be saved without an issue.

## Steps to reproduce

1. Use an earlier version of Octopus (tested on 2020.2.20)
2. Create a "Run a script" step and set the Script Source to a package
3. Upgrade to 2020.6.4788 (other versions likely also affected)
4. Change the name of the script step and attempt to save
5. Error will be generated

### Screen capture

![image](https://user-images.githubusercontent.com/20085569/114423344-01665d80-9baf-11eb-96bb-abf471188301.png)

## Affected versions

**Octopus Server:** 2020.6

## Workarounds

Setting the Script Source to "Inline" and saving, and then setting it back to "Package" will allow saves to be made again.

## Links

[Internal Link](https://octopus.zendesk.com/agent/tickets/67483)
[Internal Link](https://octopus.zendesk.com/agent/tickets/67087)
[Internal Link](https://octopus.zendesk.com/agent/tickets/66800)

**Comment by MissedTheMark** [comment] 2021-04-12 23:36
Duplicate of existing issue: https://github.com/OctopusDeploy/Issues/issues/6727

**Closed by MissedTheMark** 2021-04-12 23:36 UTC
Labels: closed/duplicate, kind/bug

**Comment by OctoStu** [comment] 2021-05-05 11:34
Another report - [Interal Link](https://octopus.zendesk.com/agent/tickets/68608)
