### ISSUE TITLE
Users cannot edit environments their team is scoped to with sufficient permissions

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#4082] opened 2017-12-14 02:12 UTC
Octopus 4.1.3

If a user has adequate permissions (EnvironmentView & EnvironmentEdit, and in my reproduction they had system administrator rights), but their team is scoped to individual environments, they're unable to edit the environments in which they're scoped to.

Repro steps:

1) Create a team, giving it the system admin role and a user
2) Scope the team to individual environments

![01_team](https://user-images.githubusercontent.com/20388190/33972127-fd996c4c-e0c7-11e7-9bea-87f01b2b3c25.png)

3) Try to edit the environment with this user

![02_edit_env](https://user-images.githubusercontent.com/20388190/33972129-012d1836-e0c8-11e7-9359-9f90f4849b37.png)

They'll hit an insufficient permissions error.

![03_error](https://user-images.githubusercontent.com/20388190/33972134-0489b322-e0c8-11e7-9c31-6627196090a5.png)

Source: https://help.octopusdeploy.com/discussions/problems/65750

**Comment by KennethBates** [comment] 2017-12-14 02:16
![](https://github.trello.services/images/mini-trello-icon.png) [Users cannot edit environments their team is scoped to with sufficient permissions](https://trello.com/c/TI98B2Jv/906-users-cannot-edit-environments-their-team-is-scoped-to-with-sufficient-permissions)

**Comment by johnsimons** [comment] 2017-12-15 06:27
Duplicate of #4091

**Closed by johnsimons** 2017-12-15 06:27 UTC
Labels: area/modelling, bug, duplicate
