### ISSUE TITLE
Tenant logos ignore max size on IE 11

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Issues#3470] opened 2017-05-05 04:20 UTC
IE 11 is ignoring the max-width and height values that are being set for Tenant logos

Below is a screenshot showing the same page in Chrome, Edge and IE 11.

<img width="1257" alt="tenant-logo" src="https://cloud.githubusercontent.com/assets/4229735/25733548/7a563416-319d-11e7-8a52-56443f8d95b8.png">

Checked project logos and it works correctly across all 3.

Source https://secure.helpscout.net/conversation/359492422/15435/?folderId=557077

**Comment by pawelpabich** [comment] 2017-05-24 22:37
Fix in v4

**Comment by droyad** [comment] 2017-09-27 06:15
Duplicate of #3170

**Closed by droyad** 2017-09-27 06:15 UTC
Labels: area/modelling, bug

**Comment by michaelnoonan** [comment] 2017-11-14 03:26
It will be fixed when 4.0.0 ships. :)
