### ISSUE TITLE
URL escaping percentage sign in branch name

### ISSUE THREAD

**Issue by LeeMeyer** [OctopusDeploy/Issues#7323] opened 2022-01-20 00:27 UTC
% is valid in a git branch name (apparently) but causes issues in our UI when we try to redirect to a branch with a percentage in the name

**Comment by StephenHeise** [comment] 2022-03-28 00:51
I have been able to fix the branch selector by changing `\app\areas\projects\context\ProjectContext.tsx`, line 157:
``` Javascript
const newUrl = generatePath(match.path, { ...match.params, branchName: encodeUriComponent(branchName) });
```
The branch selector seems to work, but it triggers this error when trying to load the Deployment Process page:
`An unexpected error occurred in Octopus v0.0.0-local: "URIError: Pathname "/Spaces-1/projects/kuri-wha/branches/kuri-%-test/deployments/process" could not be decoded. This is likely caused by an invalid percent-encoding."`
I have been unable to find exactly what is causing this. Seems to be some internal React routing thing, triggered by some automatic binding.

**Comment by YuKitsune** [comment] 2022-04-13 05:24
This is a [known issue](https://github.com/remix-run/history/issues/505) within the `history` package, which is required by `react-router`.
It's since been fixed in a later version, but it'll require us to upgrade our version of `react-router`, which is on our to-do list.

I'll close this for now since it's a low priority, and a fairly rare edge case. If we get another report, then we've got a quick interim fix ready to go: https://github.com/OctopusDeploy/OctopusDeploy/pull/11894

**Closed by YuKitsune** 2022-04-13 05:24 UTC
Labels: size/small, priority/low, team/config-as-code

**Comment by Octobob** [comment] 2022-05-10 23:41
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | _tbc_ |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment] 2022-05-10 23:45
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | _tbc_ |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment] 2022-05-10 23:52
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | _tbc_ |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment] 2022-05-11 00:04
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | _tbc_ |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment] 2022-05-11 00:07
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | _tbc_ |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment] 2022-05-11 02:19
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | 2022.1.2584 |
| 2022.2 | _tbc_ |

**Comment by Octobob** [comment] 2022-05-11 04:45
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | 2022.1.2584 |
| 2022.2 | 2022.2.5042 |

**Comment by Octobob** [comment] 2022-05-11 04:48
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | 2022.1.2584 |
| 2022.2 | 2022.2.5042 |

**Comment by Octobob** [comment] 2022-05-24 00:20
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | 2022.1.2584 |
| 2022.2 | 2022.2.5042 |
| 2022.3+ | _all releases_ |

**Comment by Octobob** [comment] 2022-05-24 00:24
:tada: The fix for this issue has been released in:

| Release stream | Release     |
| -------------- | ----------- |
| 2021.3 | 2021.3.12778 |
| 2022.1 | 2022.1.2584 |
| 2022.2 | 2022.2.5042 |
| 2022.3+ | _all releases_ |

**Comment by StephenHeise** [comment] 2022-06-20 21:53
This change has now been reverted with [this PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/12278) as it caused projects with Unicode in their names to break.
