### ISSUE TITLE
Azure CLI step fails behind authentication proxies

### ISSUE THREAD

**Issue by shaunmarx** [OctopusDeploy/Issues#4976] opened 2018-10-12 02:58 UTC
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When using an authentication proxy, Azure commands fail to login using the AWS CLI effectively failing the entire deployment.

## Steps to reproduce

Setup a proxy and ensure it requires authentication
Configure the tentacle to use the proxy
Create an Azure Powershell step and invoke any command
See error

### Log exerpt

```
Error | ERROR: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /76c076e0-5433-48c5-a9e4-d38512d229f7/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x036E85B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

## Affected versions

**Octopus Server:  2018.7.11-2018.8.8** 

## Workarounds

If using Octopus 2018.8.0 or newer you can set the OctopusDisableAzureCLI variable to True. It may also be possible to use HTTP_PROXY / HTTPS_PROXY environment variables in the format of  `http://username:password@proxy_ip:proxy_port`

## Links

Related to https://github.com/OctopusDeploy/Issues/issues/4855
First customer report https://help.octopus.com/t/issue-azure-cli-fails-to-login-when-behind-a-proxy/21493

**Comment by benPearce1** [comment] 2018-10-12 03:48
Duplicate of https://github.com/OctopusDeploy/Issues/issues/4900

**Closed by benPearce1** 2018-10-12 03:48 UTC
Labels: kind/bug, tag/regression
