### ISSUE TITLE
MultiSelect component to support Shift select

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#4086] opened 2017-12-14 04:33 UTC
## What
To make our `MultiSelect` component has the ability to select multi items at once by using `Shift+Select`, also during investigation we found that `Esc` does not close the auto complete menu, in the context of dialog, it closes the dialog instead.

## Related ticket
https://help.octopusdeploy.com/discussions/problems/65763

## Related slack discussion
https://octopusdeploy.slack.com/archives/C4WNL3PQ9/p1513224325000175

**Comment by droyad** [comment] 2019-05-10 10:08
Duplicate of #4313

**Closed by droyad** 2019-05-10 10:08 UTC
Labels: area/usability, kind/enhancement, size/small
