### ISSUE TITLE
Cannot deploy tenanted project if permissions limited to one environment that is not next in the lifecycle

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/Issues#3458] opened 2017-04-28 05:54 UTC
Source https://trello.com/c/cE7B16fS/338-permissions-user-can-t-start-deployment-as-expected

(warning: a fair bit of guess work involved in this issue description. Its reproducible though, with the details in the attached ticket)

When you have limited permissions to a single environment, limited permissions to a specific set of tenants and the permitted environment is not the next in the lifecycle, then it appears you can deploy to that environment/tenant, however it does nothing (except for log errors in the javascript console).

```
vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:110 TypeError: Cannot read property 'Links' of undefined
    at BasicRepository.getDeploymentPreview (octopus.client.js:973)
    at project_deployment_create_controller.js:257
    at Function._.map._.collect (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:716)
    at Scope.$scope.refreshPreview (project_deployment_create_controller.js:256)
    at project_deployment_create_controller.js:80
    at Object.$watchCollectionAction [as fn] (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111)
    at Scope.$digest (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111)
    at Scope.$apply (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111)
    at HTMLLIElement.<anonymous> (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:114)
    at HTMLLIElement.dispatch (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:288)
(anonymous) @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:110
(anonymous) @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:109
$digest @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111
$apply @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111
(anonymous) @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:114
dispatch @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:288
$event.dispatch @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:724
elemData.handle @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:288
```
```
vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:110 TypeError: Cannot read property 'Links' of undefined
    at BasicRepository.getDeploymentPreview (octopus.client.js:973)
    at project_deployment_create_controller.js:257
    at Function._.map._.collect (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:716)
    at Scope.$scope.refreshPreview (project_deployment_create_controller.js:256)
    at project_deployment_create_controller.js:81
    at Object.$watchCollectionAction [as fn] (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111)
    at Scope.$digest (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111)
    at Scope.$apply (vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111)
    at octopus_client.js:13
    at Object.success (octopus.client.js:377)
(anonymous) @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:110
(anonymous) @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:109
$digest @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111
$apply @ vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:111
(anonymous) @ octopus_client.js:13
success @ octopus.client.js:377
request.onreadystatechange @ octopus.client.js:235
```

```
vendor.0-53-a843531175440ab.hashedasset.js:sourcemap:110 TypeError: Cannot read property 'filter' of undefined
    at createDeployment (http://master.octopushq.com/application.0-53-0a73f9067a14196.hashedasset.js:24:3879)
    at http://master.octopushq.com/application.0-53-0a73f9067a14196.hashedasset.js:24:5095
    at Array.map (native)
    at http://master.octopushq.com/application.0-53-0a73f9067a14196.hashedasset.js:24:5065
    at processQueue (http://master.octopushq.com/vendor.0-53-a843531175440ab.hashedasset.js:110:23475)
    at http://master.octopushq.com/vendor.0-53-a843531175440ab.hashedasset.js:110:23742
    at Scope.$eval (http://master.octopushq.com/vendor.0-53-a843531175440ab.hashedasset.js:111:4833)
    at Scope.$digest (http://master.octopushq.com/vendor.0-53-a843531175440ab.hashedasset.js:111:2573)
    at Scope.$apply (http://master.octopushq.com/vendor.0-53-a843531175440ab.hashedasset.js:111:5238)
    at HTMLFormElement.<anonymous> (http://master.octopushq.com/vendor.0-53-a843531175440ab.hashedasset.js:114:8073)
```

It shows an error message as expected when you have full permissions, but with limited permissions, it crashes.

normal error message:
![image](https://cloud.githubusercontent.com/assets/373389/25515941/d99b8b7e-2c2a-11e7-9174-7e82f0eba758.png)

I think that https://github.com/OctopusDeploy/OctopusDeploy/blob/abd1456d3484f7e3194cebe34c3d26b88cc1bbb4/portal/app/areas/projects/controllers/project_deployment_create_controller.js#L56 needs to check whether its a tenanted deployment, and if so, get it from `$scope.template.TenantPromotions` instead.

**Comment by michaelnoonan** [comment] 2017-07-06 04:51
This may have already been fixed in #3632

**Comment by MJRichardson** [comment] 2017-10-03 02:24
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot deploy tenanted project if permissions limited to one environment that is not next in the lifecycle](https://trello.com/c/Hc2yVphh/719-cannot-deploy-tenanted-project-if-permissions-limited-to-one-environment-that-is-not-next-in-the-lifecycle)

**Comment by MJRichardson** [comment] 2017-10-31 03:49
I was unabled to replicate this.

My steps:

1. Create a tenanted project with lifecycle as:
    - Dev
   - Test A
   - Test B
2. Created a user with permissions restricted to tenant and Test B environment
3. Deployed Release to Dev
4. Logged in with restricted-user.  On the release page, the 'Deploy to Test B' button was shown (even though this environment is not eligible).
5. Attempted to deploy

The result was as shown below. 

> The release has not been deployed to the required environments before it can be promoted to this environment

This is the expected behaviour.  Though you could possibly argue the deploy button shouldn't be shown at all.

![tenant-permission-progression](https://user-images.githubusercontent.com/113759/32206648-08299a2c-be42-11e7-8cbc-169aef3d52ef.png)

**Comment by MJRichardson** [comment] 2017-11-03 05:37
I think the root cause here is due to the way release-progression is calculated when there are environments the user doesn't have permissions for.   This may be specific to the default lifecycle, as that was the way I could reproduce it (though it may also be possible in other scenarios).

As an example, if the lifecycle-progression for a (non-tenanted) project looks like:

![image](https://user-images.githubusercontent.com/113759/32361430-03437c14-c0ac-11e7-9419-f9a627bb8fb2.png)

When viewing with a user which does not have permission to the `Test A` or `Test B` environments, it appears as:

![image](https://user-images.githubusercontent.com/113759/32361440-2f206806-c0ac-11e7-9b7a-02d639312fa2.png)

Obviously the "Promote to Staging" button should _not_ be shown, as the release is not eligible to be deployed to staging.  But how would we show that to the user if they can't see the intermediate environments?

Resolving this will take a re-think of the permissions model.  

In the future, it is likely environments will no longer be global, but will leave within a space (or system, or project-group, or whatever the final name is).  This will be the logical time to reconsider permissions.

I think the answer will be if you have permission to view the space, then you have permission to view all the environments within the space.

**Comment by johnsimons** [comment] 2018-01-16 22:35
@MJRichardson so it seems in v4 we are actually showing phases that contain environments the user has no access to.
So I am testing this with a user that can only see Development and Production:
![image](https://user-images.githubusercontent.com/122651/35015615-e2c61682-fb60-11e7-905f-3ec7c640d066.png)
When I go to deploy the release I get:
![image](https://user-images.githubusercontent.com/122651/35015656-0b84e5da-fb61-11e7-95e1-61a2858565c5.png)
If I try to deploy to Staging, the following screen shows "Missing Resource" and fails with error message:
![image](https://user-images.githubusercontent.com/122651/35015701-44435942-fb61-11e7-9087-4310be149ce6.png)

**Comment by TomPeters** [comment] 2019-05-08 05:59
This is still a bug on `2019.4.7`
![2019-05-08_15-58-56](https://user-images.githubusercontent.com/1892715/57352928-41925980-71aa-11e9-9de7-ac15d70525c9.gif)

**Closed** 2022-02-22 06:01 UTC
Labels: kind/bug, feature/tenants, tag/permissions, size/medium, feature/lifecycle, area/core, team/fire-and-motion
