### ISSUE TITLE
Inconsistent behaviour for Step Template variables for Azure Accounts

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#4585] opened 2018-05-23 06:42 UTC
Scenario:
Create a new step template based upon the Azure PowerShell Script step. 
Create a new Azure Account parameter and bind the Account on the step to the input parameter
On the project, create an Azure Account variable and then set this variable as account on the new templated step.

Creating the deployment will error with _Couldn't find an account with the Id zzz_ where zzz is the name of the project variable.

Workaround for this issue is to bind the account field to the project variable with binding syntax _#{project variable name}_

**Comment by johnsimons** [comment] 2019-01-31 21:52
This seems to be duplicate of #4458.
@shaunmarx @benPearce1 thoughts?

**Comment by benPearce1** [comment] 2019-01-31 22:39
@johnsimons This one suggests that there is an unexpected error message in a specific scenario, so I think they may be different

**Comment by johnsimons** [comment] 2019-01-31 22:43
@benPearce1 are you referring to https://github.com/OctopusDeploy/Issues/issues/4117 ?

**Comment by benPearce1** [comment] 2019-01-31 22:47
@johnsimons this one and #4117 seem to be related, but #4458 is different

**Comment by zentron** [comment] 2019-05-23 08:02
This no longer appears to be a problem. Closing as invalid as it is un-reproducable. It may be been fixed since this ticket was first logged

**Closed by zentron** 2019-05-23 08:02 UTC
Labels: closed/invalid, kind/enhancement
