### ISSUE TITLE
Offline drop target name can have FileSystem Path characters which cause problem

### ISSUE THREAD

**Issue by mayuanyang** [OctopusDeploy/Issues#3890] opened 2017-10-27 04:11 UTC
When deploying to an offline drop target, OD uses the target name to create the folder, any FileSystem Path characters will cause the folder cannot be created and failed the deployment

**Comment by droyad** [comment] 2018-01-10 03:18
Duplicate of #3929 ?

**Comment by mayuanyang** [comment] 2018-01-10 03:43
@droyad a little bit different, one for project name and one for target name

**Comment by droyad** [comment] 2018-01-16 00:17
It's the same underlying cause, so marking as duplicate of #3929

**Closed by droyad** 2018-01-16 00:17 UTC
Labels: area/execution, bash, bug, feature/offline-drop

**Comment by droyad** [comment] 2018-01-16 00:22
Release Note: Offline drops now removed invalid characters from the project and target names used for filenames
