### ISSUE TITLE
New Tentacle running against old Server throws exception

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#3582] opened 2017-06-21 22:19 UTC
```
2017-06-21 12:02:44.3432 11 FATAL Unhandled AppDomain exception occurred: Value cannot be null. 
System.ArgumentNullException: Value cannot be null. 
Parameter name: key 
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAdd(TKey key, TValue value) 
   at Octopus.Shared.Scripts.ScriptIsolationMutex.TaskLock.TryEnterReadLock(String taskId, TimeSpan timeout, CancellationToken cancellationToken, IDisposable& releaseLock) 
   at Octopus.Shared.Scripts.ScriptIsolationMutex.ScriptIsolationMutexReleaser.EnterReadLock()
   at Octopus.Shared.Scripts.ScriptIsolationMutex.ScriptIsolationMutexReleaser.EnterLock()
   at Octopus.Shared.Scripts.ScriptIsolationMutex.Acquire(ScriptIsolationLevel isolation, TimeSpan mutexAcquireTimeout, String lockName, Action`1 taskLog, String taskId, CancellationToken token) 
   at Octopus.Shared.Scripts.RunningScript.Execute() 
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by droyad** [comment] 2017-07-03 04:25
duplicate of https://github.com/OctopusDeploy/OctopusTentacle/issues/13

**Closed by droyad** 2017-07-03 04:25 UTC
Labels: area/execution
