### ISSUE TITLE
Drop down when deploying a release does not populate automatically

### ISSUE THREAD

**Issue by ziaulislamOctopus** [OctopusDeploy/Issues#5884] opened 2019-10-02 04:40 UTC
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When trying to select a version of release you would like to deploy to for tenants you have to manually type out the release number rather than clicking the button to give you a list of release versions.

![ReleaseNotLoading](https://user-images.githubusercontent.com/55085140/66018389-2e4da500-e522-11e9-8e0b-976ab906a511.gif)

## What I expected to happen

By clicking onto the drop down it should show you a list of releases avaliable to deploy.

## Replicate Issue

1. Go to 'Your Project'
2. Click on 'Release'
3. Scroll down to 'Filter by release'

## Links
https://secure.helpscout.net/conversation/969410131/50906?folderId=3209064

**Comment by droyad** [comment] 2019-10-02 04:47
Duplicate of #5601

**Closed by droyad** 2019-10-02 04:47 UTC
Labels: area/usability, kind/bug
